# -*- coding: utf-8 -*-
"""PostgreSQL storage for account-operation task instances.

Only task state, stage events and redacted result summaries are stored here.
Passwords, access tokens, OTPs, mailbox bodies and credentialed proxy URLs are
never persisted.
"""
from __future__ import annotations

import json
import os
import re
import threading
import uuid
from datetime import datetime
from typing import Any

from core import postgres_store
from core.task_stages import normalize_step_state

_LOCK = threading.RLock()
_SCHEMA = str(os.getenv("ACCOUNT_TASK_DB_SCHEMA") or "public").strip() or "public"
_READY_KEY = ""

_TERMINAL_STATUSES = {"success", "failed", "deactivated", "unsupported", "cancelled", "interrupted"}
_SECRET_KEY_PARTS = ("password", "otp", "secret", "authorization", "cookie")
_PROXY_CREDENTIAL_RE = re.compile(r"(?P<scheme>https?://)[^/@\s]+@", re.IGNORECASE)
_PROXY_AUTH_RE = re.compile(r"(?<![\w/])[^\s:@/]+:[^\s@/]+@")
_PROXY_FOUR_PART_RE = re.compile(r"(?P<endpoint>(?:\d{1,3}\.){3}\d{1,3}:\d+):[^:\s]+:[^:\s]+")
_JWT_RE = re.compile(r"\beyJ[A-Za-z0-9_-]{12,}\.[A-Za-z0-9_-]{12,}\.[A-Za-z0-9_-]{8,}\b")
_IDENTIFIER_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def _schema() -> str:
    if not _IDENTIFIER_RE.fullmatch(_SCHEMA):
        raise ValueError("ACCOUNT_TASK_DB_SCHEMA 不是合法 PostgreSQL schema 名称")
    return f'"{_SCHEMA}"'


def _table(name: str) -> str:
    if not _IDENTIFIER_RE.fullmatch(name):
        raise ValueError("非法 PostgreSQL 表名")
    return f'{_schema()}."{name}"'


def _index(name: str) -> str:
    if not _IDENTIFIER_RE.fullmatch(name):
        raise ValueError("非法 PostgreSQL 索引名")
    return f'"{name}"'


def _connect():
    from psycopg.rows import dict_row
    return postgres_store.connect(row_factory=dict_row)


def _sync_operation_task(task_id: int | None) -> None:
    """迁移期兼容桥：账号任务旧投影更新后刷新统一任务中心。"""
    if not task_id:
        return
    # 旧账号任务测试会单独 monkeypatch _SCHEMA。两套模型不在同一 schema 时不能
    # 跨到 public 或其它测试 schema 写投影；正式运行时二者都是 public。
    if _SCHEMA != postgres_store.schema_name():
        return
    try:
        from core.storage import operation_projection

        operation_projection.sync_account_task(int(task_id))
    except Exception:
        import logging

        logging.getLogger(__name__).exception("同步统一任务中心失败：account_task_id=%s", task_id)


def init() -> None:
    global _READY_KEY
    if not postgres_store.enabled():
        raise RuntimeError("账号任务存储需要配置可用的 DATABASE_URL")
    ready_key = f"{postgres_store.database_url()}::{_SCHEMA}"
    with _LOCK:
        if _READY_KEY == ready_key:
            return
        batches = _table("account_action_batches")
        tasks = _table("account_action_tasks")
        events = _table("account_action_events")
        with _connect() as conn, conn.cursor() as cur:
            cur.execute(f"CREATE SCHEMA IF NOT EXISTS {_schema()}")
            cur.execute(f"SET LOCAL search_path TO {_schema()}, public")
            cur.execute(
                f"""
                CREATE TABLE IF NOT EXISTS {batches} (
                    id TEXT PRIMARY KEY,
                    action_type TEXT NOT NULL,
                    trigger TEXT NOT NULL,
                    total_count INTEGER NOT NULL DEFAULT 0,
                    queued_count INTEGER NOT NULL DEFAULT 0,
                    running_count INTEGER NOT NULL DEFAULT 0,
                    success_count INTEGER NOT NULL DEFAULT 0,
                    failed_count INTEGER NOT NULL DEFAULT 0,
                    created_at TEXT NOT NULL,
                    completed_at TEXT
                )
                """
            )
            cur.execute(
                f"""
                CREATE TABLE IF NOT EXISTS {tasks} (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    task_uuid TEXT NOT NULL UNIQUE,
                    batch_id TEXT,
                    task_type TEXT NOT NULL,
                    account_id BIGINT,
                    email_snapshot TEXT NOT NULL DEFAULT '',
                    trigger TEXT NOT NULL,
                    status TEXT NOT NULL,
                    validation_method TEXT,
                    network_route TEXT,
                    proxy_mode TEXT,
                    proxy_provider TEXT,
                    proxy_region TEXT,
                    proxy_used TEXT,
                    result_summary JSONB,
                    error TEXT,
                    queued_at TEXT NOT NULL,
                    started_at TEXT,
                    finished_at TEXT,
                    duration_ms INTEGER,
                    CONSTRAINT account_action_tasks_batch_fk FOREIGN KEY (batch_id)
                        REFERENCES {batches}(id)
                )
                """
            )
            cur.execute(
                f"""
                CREATE TABLE IF NOT EXISTS {events} (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    task_id BIGINT NOT NULL,
                    created_at TEXT NOT NULL,
                    level TEXT NOT NULL,
                    stage TEXT NOT NULL,
                    message TEXT NOT NULL,
                    detail JSONB,
                    CONSTRAINT account_action_events_task_fk FOREIGN KEY (task_id)
                        REFERENCES {tasks}(id) ON DELETE CASCADE
                )
                """
            )
            cur.execute(f"CREATE INDEX IF NOT EXISTS {_index('idx_account_tasks_created')} ON {tasks}(id DESC)")
            cur.execute(f"CREATE INDEX IF NOT EXISTS {_index('idx_account_tasks_account')} ON {tasks}(account_id, id DESC)")
            cur.execute(f"CREATE INDEX IF NOT EXISTS {_index('idx_account_tasks_status')} ON {tasks}(status, id DESC)")
            cur.execute(f"CREATE INDEX IF NOT EXISTS {_index('idx_account_task_events_task')} ON {events}(task_id, id)")
        _READY_KEY = ready_key


def _now() -> str:
    return datetime.now().isoformat(timespec="seconds")


def _redact_text(value: object, limit: int = 1000) -> str:
    text = str(value or "")
    text = _PROXY_CREDENTIAL_RE.sub(r"\g<scheme>***@", text)
    text = _JWT_RE.sub("[REDACTED_AT]", text)
    return text[:limit]


def _redact_proxy(value: object) -> str:
    text = _redact_text(value, 220)
    text = _PROXY_AUTH_RE.sub("***:***@", text)
    return _PROXY_FOUR_PART_RE.sub(r"\g<endpoint>:***:***", text)


def _scrub(value: Any, depth: int = 0) -> Any:
    if depth > 4:
        return "[truncated]"
    if isinstance(value, dict):
        out = {}
        for raw_key, raw_value in list(value.items())[:80]:
            key = str(raw_key)
            lowered = key.lower()
            if (
                any(part in lowered for part in _SECRET_KEY_PARTS)
                or lowered in {"token", "access_token", "refresh_token", "id_token"}
                or lowered.endswith("_access_token")
                or lowered.endswith("_refresh_token")
            ):
                continue
            if lowered in {"proxy", "proxy_url", "proxy_used"}:
                out[key[:80]] = _redact_proxy(raw_value)
                continue
            out[key[:80]] = _scrub(raw_value, depth + 1)
        return out
    if isinstance(value, (list, tuple)):
        return [_scrub(item, depth + 1) for item in list(value)[:80]]
    if isinstance(value, (str, bytes)):
        return _redact_text(value, 1000)
    if value is None or isinstance(value, (bool, int, float)):
        return value
    return _redact_text(value, 300)


def _json(value: Any) -> str | None:
    if value is None:
        return None
    return json.dumps(_scrub(value), ensure_ascii=False, separators=(",", ":"))


def _decode_json(value: Any) -> Any:
    if value is None:
        return None
    if isinstance(value, (dict, list)):
        return value
    try:
        return json.loads(value)
    except (TypeError, ValueError):
        return None


def _decode_row(row: dict | None) -> dict | None:
    if row is None:
        return None
    item = dict(row)
    for key in ("result_summary", "detail"):
        if key in item:
            item[key] = _decode_json(item[key])
    return item


def create_batch(*, action_type: str, trigger: str, total_count: int) -> str:
    init()
    batch_id = uuid.uuid4().hex
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            f"INSERT INTO {_table('account_action_batches')} "
            "(id, action_type, trigger, total_count, created_at) VALUES (%s, %s, %s, %s, %s)",
            (batch_id, str(action_type), str(trigger), max(0, int(total_count)), _now()),
        )
    return batch_id


def create_task(*, task_type: str, account_id: int | None, email: str, trigger: str, batch_id: str | None = None) -> int:
    init()
    now = _now()
    tasks = _table("account_action_tasks")
    events = _table("account_action_events")
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            f"INSERT INTO {tasks} (task_uuid, batch_id, task_type, account_id, email_snapshot, trigger, status, queued_at) "
            "VALUES (%s, %s, %s, %s, %s, %s, 'queued', %s) RETURNING id",
            (uuid.uuid4().hex, batch_id, str(task_type or "unknown")[:60],
             int(account_id) if account_id is not None else None, str(email or "")[:320],
             str(trigger or "manual")[:80], now),
        )
        task_id = int(cur.fetchone()["id"])
        cur.execute(
            f"INSERT INTO {events} (task_id, created_at, level, stage, message) "
            "VALUES (%s, %s, 'INFO', 'queued', %s)",
            (task_id, now, "任务已加入队列"),
        )
        _refresh_batch(cur, batch_id)
    _sync_operation_task(task_id)
    return task_id


def append_event(
    task_id: int | None,
    *,
    stage: str,
    message: str,
    level: str = "INFO",
    detail: dict | None = None,
    state: str | None = None,
) -> None:
    """写入脱敏事件；流程节点必须用 ``state`` 明确表达五态。"""
    if not task_id:
        return
    init()
    clean_detail = dict(detail or {})
    if state is not None:
        normalized_state = normalize_step_state(state)
        if normalized_state is None:
            raise ValueError(f"不支持的任务步骤状态: {state!r}")
        clean_detail["step_state"] = normalized_state
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            f"INSERT INTO {_table('account_action_events')} (task_id, created_at, level, stage, message, detail) "
            "VALUES (%s, %s, %s, %s, %s, %s::jsonb)",
            (int(task_id), _now(), str(level or "INFO").upper()[:16], str(stage or "event")[:80],
             _redact_text(message, 1200), _json(clean_detail)),
        )
    _sync_operation_task(int(task_id))


def start_task(task_id: int | None, *, message: str = "开始执行") -> None:
    if not task_id:
        return
    init()
    now = _now()
    tasks = _table("account_action_tasks")
    events = _table("account_action_events")
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(f"SELECT batch_id FROM {tasks} WHERE id=%s", (int(task_id),))
        row = cur.fetchone()
        if row is None:
            return
        cur.execute(f"UPDATE {tasks} SET status='running', started_at=%s WHERE id=%s", (now, int(task_id)))
        cur.execute(
            f"INSERT INTO {events} (task_id, created_at, level, stage, message) "
            "VALUES (%s, %s, 'INFO', 'running', %s)",
            (int(task_id), now, _redact_text(message, 1200)),
        )
        _refresh_batch(cur, row["batch_id"])
    _sync_operation_task(int(task_id))


def _duration_ms(started_at: str | None, finished_at: str) -> int | None:
    if not started_at:
        return None
    try:
        return max(0, int((datetime.fromisoformat(finished_at) - datetime.fromisoformat(started_at)).total_seconds() * 1000))
    except (TypeError, ValueError):
        return None


def finish_task(task_id: int | None, *, status: str, message: str, error: str | None = None,
                result_summary: dict | None = None, route: dict | None = None,
                validation_method: str | None = None) -> None:
    if not task_id:
        return
    init()
    final_status = str(status or "failed").lower()
    if final_status not in _TERMINAL_STATUSES:
        final_status = "failed"
    now = _now()
    route = _scrub(route or {})
    tasks = _table("account_action_tasks")
    events = _table("account_action_events")
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(f"SELECT batch_id, started_at FROM {tasks} WHERE id=%s", (int(task_id),))
        row = cur.fetchone()
        if row is None:
            return
        cur.execute(
            f"UPDATE {tasks} SET status=%s, validation_method=%s, network_route=%s, proxy_mode=%s, "
            "proxy_provider=%s, proxy_region=%s, proxy_used=%s, result_summary=%s::jsonb, error=%s, "
            "finished_at=%s, duration_ms=%s WHERE id=%s",
            (final_status, str(validation_method or "")[:80] or None,
             str(route.get("network_route") or "")[:80] or None,
             str(route.get("proxy_mode") or "")[:80] or None,
             str(route.get("proxy_provider") or "")[:80] or None,
             str(route.get("proxy_region") or "")[:80] or None,
             _redact_proxy(route.get("proxy_used")) or None, _json(result_summary),
             _redact_text(error, 1200) or None, now,
             _duration_ms(row["started_at"], now), int(task_id)),
        )
        cur.execute(
            f"INSERT INTO {events} (task_id, created_at, level, stage, message, detail) "
            "VALUES (%s, %s, %s, 'complete', %s, %s::jsonb)",
            (int(task_id), now, "ERROR" if final_status in {"failed", "interrupted"} else "INFO",
             _redact_text(message, 1200), _json(result_summary)),
        )
        _refresh_batch(cur, row["batch_id"])
    _sync_operation_task(int(task_id))


def _refresh_batch(cur, batch_id: str | None) -> None:
    if not batch_id:
        return
    cur.execute(
        f"SELECT status, COUNT(*) AS n FROM {_table('account_action_tasks')} WHERE batch_id=%s GROUP BY status",
        (batch_id,),
    )
    counts = {str(row["status"]): int(row["n"]) for row in cur.fetchall()}
    queued = counts.get("queued", 0)
    running = counts.get("running", 0)
    success = counts.get("success", 0)
    failed = sum(counts.get(key, 0) for key in ("failed", "deactivated", "unsupported", "cancelled", "interrupted"))
    completed_at = _now() if queued == 0 and running == 0 and (success + failed) > 0 else None
    cur.execute(
        f"UPDATE {_table('account_action_batches')} SET queued_count=%s, running_count=%s, "
        "success_count=%s, failed_count=%s, completed_at=%s WHERE id=%s",
        (queued, running, success, failed, completed_at, batch_id),
    )


def recover_interrupted() -> int:
    init()
    now = _now()
    tasks = _table("account_action_tasks")
    events = _table("account_action_events")
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(f"SELECT id, batch_id, started_at FROM {tasks} WHERE status IN ('queued','running')")
        rows = cur.fetchall()
        for row in rows:
            cur.execute(
                f"UPDATE {tasks} SET status='interrupted', error=%s, finished_at=%s, duration_ms=%s WHERE id=%s",
                ("WebUI 重启导致任务中断，请重新执行", now, _duration_ms(row["started_at"], now), int(row["id"])),
            )
            cur.execute(
                f"INSERT INTO {events} (task_id, created_at, level, stage, message) VALUES (%s, %s, 'ERROR', 'interrupted', %s)",
                (int(row["id"]), now, "WebUI 重启导致任务中断，请重新执行"),
            )
        for batch_id in {row["batch_id"] for row in rows if row["batch_id"]}:
            _refresh_batch(cur, batch_id)
    for row in rows:
        _sync_operation_task(int(row["id"]))
    return len(rows)


def list_tasks(*, page: int = 1, page_size: int = 50, task_type: str = "", status: str = "", q: str = "") -> dict:
    init()
    page = max(1, int(page or 1))
    page_size = max(1, min(200, int(page_size or 50)))
    where: list[str] = []
    params: list[Any] = []
    if task_type:
        where.append("task_type=%s")
        params.append(str(task_type))
    if status:
        where.append("status=%s")
        params.append(str(status))
    if q:
        where.append("(email_snapshot ILIKE %s OR CAST(account_id AS TEXT) ILIKE %s OR CAST(id AS TEXT) ILIKE %s)")
        needle = f"%{str(q).strip()}%"
        params.extend((needle, needle, needle))
    clause = f" WHERE {' AND '.join(where)}" if where else ""
    tasks = _table("account_action_tasks")
    offset = (page - 1) * page_size
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(f"SELECT COUNT(*) AS n FROM {tasks}{clause}", params)
        total = int(cur.fetchone()["n"])
        cur.execute(
            f"SELECT id, task_uuid, batch_id, task_type, account_id, email_snapshot, trigger, status, "
            "validation_method, network_route, proxy_mode, proxy_provider, proxy_region, proxy_used, "
            f"result_summary, error, queued_at, started_at, finished_at, duration_ms FROM {tasks}{clause} "
            "ORDER BY id DESC LIMIT %s OFFSET %s",
            (*params, page_size, offset),
        )
        rows = cur.fetchall()
    return {"ok": True, "items": [_decode_row(row) for row in rows], "total": total, "page": page, "page_size": page_size}


def get_task(task_id: int) -> dict | None:
    init()
    tasks = _table("account_action_tasks")
    events = _table("account_action_events")
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            f"SELECT id, task_uuid, batch_id, task_type, account_id, email_snapshot, trigger, status, "
            "validation_method, network_route, proxy_mode, proxy_provider, proxy_region, proxy_used, "
            f"result_summary, error, queued_at, started_at, finished_at, duration_ms FROM {tasks} WHERE id=%s",
            (int(task_id),),
        )
        task = cur.fetchone()
        if task is None:
            return None
        cur.execute(
            f"SELECT id, task_id, created_at, level, stage, message, detail FROM {events} WHERE task_id=%s ORDER BY id",
            (int(task_id),),
        )
        event_rows = cur.fetchall()
    item = _decode_row(task) or {}
    item["events"] = [_decode_row(row) for row in event_rows]
    return item
