"""注册、Codex 与查活共用的 Selenium 认证能力入口。

实现位于 :mod:`core.registration.auth_capabilities`，本模块只保留稳定的
公开名称。它不再反向加载 Roxy 编排模块；旧调用方可以继续从这里导入原有
能力名，并可在此模块上直接 monkeypatch。
"""
from __future__ import annotations

from .auth_capabilities import (
    AuthErrorCode,
    AuthExecutionContext,
    AuthStepResult,
    Cancellation,
    CancellationRequested,
    PageState,
    StepResult,
    StageBudget,
    StageTimeout,
    build_driver,
    quit_driver,
    center_browser_window,
    safe_get,
    page_warmup,
    find_any,
    click_any,
    type_any,
    human_click,
    human_type_text,
    click_email_entry_option,
    type_email_address,
    submit_email_step,
    recover_email_submit_if_stuck,
    submit_email_via_browser_nextauth,
    submit_email_and_wait_next,
    wait_email_submit_next_state,
    type_otp,
    email_otp_page_state,
    clear_otp_inputs,
    click_resend_email_otp,
    wait_after_email_otp_submit,
    click_continue,
    maybe_accept,
    has_access_token,
    is_email_verification_page,
    is_login_password_page,
    click_passwordless_signup_if_present,
    fill_password_page_if_present,
    complete_profile_page,
    fetch_chatgpt_session,
    check_manual_stop,
    registration_password,
    set_login_password,
    setup_roxy_2fa,
    setup_protocol_2fa_with_browser_fallback,
    checkpoint,
    execution_context,
)

__all__ = [
    "PageState",
    "AuthErrorCode",
    "AuthExecutionContext",
    "AuthStepResult",
    "Cancellation",
    "CancellationRequested",
    "StepResult",
    "StageBudget",
    "StageTimeout",
    "build_driver",
    "quit_driver",
    "center_browser_window",
    "safe_get",
    "page_warmup",
    "find_any",
    "click_any",
    "type_any",
    "human_click",
    "human_type_text",
    "click_email_entry_option",
    "type_email_address",
    "submit_email_step",
    "recover_email_submit_if_stuck",
    "submit_email_via_browser_nextauth",
    "submit_email_and_wait_next",
    "wait_email_submit_next_state",
    "type_otp",
    "email_otp_page_state",
    "clear_otp_inputs",
    "click_resend_email_otp",
    "wait_after_email_otp_submit",
    "click_continue",
    "maybe_accept",
    "has_access_token",
    "is_email_verification_page",
    "is_login_password_page",
    "click_passwordless_signup_if_present",
    "fill_password_page_if_present",
    "complete_profile_page",
    "fetch_chatgpt_session",
    "check_manual_stop",
    "registration_password",
    "set_login_password",
    "setup_roxy_2fa",
    "setup_protocol_2fa_with_browser_fallback",
    "checkpoint",
    "execution_context",
]
