# -*- coding: utf-8 -*-
"""统一任务中心的 PostgreSQL 存储与旧模型兼容投影。

新模型把批次、逻辑任务、执行实例和事件分开。注册尝试独立于执行实例，因而一次
执行失败不会再被误解为远端账号不存在。迁移期保留 registration_jobs 和
account_action_* 作为兼容写入口；本模块幂等同步、校验并为新任务中心提供唯一读模型。
"""
from __future__ import annotations

import json
import os
import re
import threading
import uuid
from datetime import datetime, timezone
from typing import Any, Iterable

from core import account_task_store, postgres_store, record_store
from core.task_errors import classify_task_error
from core.task_stages import flow_for, normalize_stage, normalize_step_state


_LOCK = threading.RLock()
_READY_KEY = ""
_IDENTIFIER_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
_SCHEMA_ENV = "OPERATION_TASK_DB_SCHEMA"
_TERMINAL_STATUSES = {
    "success", "partial_success", "failed", "stopped", "cancelled", "interrupted",
    "deactivated", "unsupported", "attention_required",
}
_SECRET_PARTS = ("password", "otp", "secret", "authorization", "cookie", "token")
_JWT_RE = re.compile(r"\beyJ[A-Za-z0-9_-]{12,}\.[A-Za-z0-9_-]{12,}\.[A-Za-z0-9_-]{8,}\b")
_PROXY_RE = re.compile(r"(?P<scheme>https?://)[^/@\s]+@", re.IGNORECASE)


def _schema_name() -> str:
    value = str(os.getenv(_SCHEMA_ENV) or postgres_store.schema_name()).strip() or "public"
    if not _IDENTIFIER_RE.fullmatch(value):
        raise ValueError("OPERATION_TASK_DB_SCHEMA 不是合法 PostgreSQL schema 名称")
    return value


def _quote(value: str) -> str:
    if not _IDENTIFIER_RE.fullmatch(value):
        raise ValueError(f"非法 PostgreSQL 标识符: {value!r}")
    return f'"{value}"'


def _table(name: str) -> str:
    return f"{_quote(_schema_name())}.{_quote(name)}"


def _connect():
    from psycopg.rows import dict_row

    return postgres_store.connect(row_factory=dict_row)


def _now() -> datetime:
    return datetime.now(timezone.utc)


def _uuid(kind: str, source: object) -> str:
    return uuid.uuid5(uuid.NAMESPACE_URL, f"turb-console:{kind}:{source}").hex


def _text(value: Any, limit: int = 1200) -> str:
    text = _JWT_RE.sub("[REDACTED_TOKEN]", str(value or ""))
    text = _PROXY_RE.sub(r"\g<scheme>***@", text)
    return text[:limit]


def _scrub(value: Any, depth: int = 0) -> Any:
    if depth > 5:
        return "[truncated]"
    if isinstance(value, dict):
        out: dict[str, Any] = {}
        for raw_key, raw_value in list(value.items())[:120]:
            key = str(raw_key)[:100]
            lowered = key.lower()
            if any(part in lowered for part in _SECRET_PARTS):
                continue
            out[key] = _scrub(raw_value, depth + 1)
        return out
    if isinstance(value, (list, tuple)):
        return [_scrub(item, depth + 1) for item in list(value)[:120]]
    if isinstance(value, (str, bytes)):
        return _text(value, 2000)
    if value is None or isinstance(value, (bool, int, float)):
        return value
    return _text(value, 500)


def _json(value: Any) -> str:
    return json.dumps(_scrub(value), ensure_ascii=False, separators=(",", ":"))


def _decode(value: Any) -> Any:
    if value is None or isinstance(value, (dict, list)):
        return value
    try:
        return json.loads(value)
    except (TypeError, ValueError):
        return value


def _row(row: dict | None) -> dict | None:
    if row is None:
        return None
    result = dict(row)
    for key in ("next_actions", "progress_steps", "result_summary", "detail", "data"):
        if key in result:
            result[key] = _decode(result[key])
    for key, value in list(result.items()):
        if isinstance(value, datetime):
            result[key] = value.isoformat()
    return result


def reset_ready() -> None:
    global _READY_KEY
    with _LOCK:
        _READY_KEY = ""


def init() -> None:
    """幂等创建统一模型；只加表和索引，不改旧表。"""
    global _READY_KEY
    if not postgres_store.enabled():
        raise RuntimeError("统一任务存储需要配置可用的 DATABASE_URL")
    # 原生运行态会更新账号三轴状态，先确保 registered_accounts 已有对应提升列。
    record_store.init()
    # 迁移桥会读取旧账号任务表；全新数据库也必须先具备这三张兼容表。
    account_task_store.init()
    ready_key = f"{postgres_store.database_url()}::{_schema_name()}"
    with _LOCK:
        if _READY_KEY == ready_key:
            return
        schema = _quote(_schema_name())
        with _connect() as conn, conn.cursor() as cur:
            cur.execute(f"CREATE SCHEMA IF NOT EXISTS {schema}")
            cur.execute(
                f"""
                CREATE TABLE IF NOT EXISTS {_table('registration_attempts')} (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    attempt_uuid TEXT NOT NULL UNIQUE,
                    source_root_job_id BIGINT UNIQUE,
                    email_snapshot TEXT NOT NULL DEFAULT '',
                    account_id BIGINT,
                    root_task_id BIGINT,
                    checkpoint TEXT NOT NULL DEFAULT 'unknown',
                    remote_identity_state TEXT NOT NULL DEFAULT 'unknown',
                    remote_account_state TEXT NOT NULL DEFAULT 'unknown',
                    local_account_state TEXT NOT NULL DEFAULT 'missing',
                    target_status TEXT NOT NULL DEFAULT 'unknown',
                    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                    completed_at TIMESTAMPTZ,
                    data JSONB NOT NULL DEFAULT '{{}}'::jsonb
                )
                """
            )
            cur.execute(
                f"""
                CREATE TABLE IF NOT EXISTS {_table('operation_batches')} (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    batch_uuid TEXT NOT NULL UNIQUE,
                    source_system TEXT NOT NULL,
                    source_id TEXT NOT NULL,
                    batch_type TEXT NOT NULL,
                    title TEXT NOT NULL,
                    status TEXT NOT NULL DEFAULT 'queued',
                    requested_count INTEGER NOT NULL DEFAULT 0,
                    queued_count INTEGER NOT NULL DEFAULT 0,
                    running_count INTEGER NOT NULL DEFAULT 0,
                    success_count INTEGER NOT NULL DEFAULT 0,
                    partial_count INTEGER NOT NULL DEFAULT 0,
                    failed_count INTEGER NOT NULL DEFAULT 0,
                    attention_count INTEGER NOT NULL DEFAULT 0,
                    stopped_count INTEGER NOT NULL DEFAULT 0,
                    cancelled_count INTEGER NOT NULL DEFAULT 0,
                    skipped_count INTEGER NOT NULL DEFAULT 0,
                    created_by TEXT NOT NULL DEFAULT 'migration',
                    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                    completed_at TIMESTAMPTZ,
                    data JSONB NOT NULL DEFAULT '{{}}'::jsonb,
                    UNIQUE(source_system, source_id)
                )
                """
            )
            cur.execute(
                f"ALTER TABLE {_table('operation_batches')} ADD COLUMN IF NOT EXISTS skipped_count INTEGER NOT NULL DEFAULT 0"
            )
            cur.execute(
                f"""
                CREATE TABLE IF NOT EXISTS {_table('operation_tasks')} (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    task_uuid TEXT NOT NULL UNIQUE,
                    source_system TEXT NOT NULL,
                    source_id TEXT NOT NULL,
                    batch_id BIGINT REFERENCES {_table('operation_batches')}(id),
                    parent_task_id BIGINT REFERENCES {_table('operation_tasks')}(id),
                    root_task_id BIGINT REFERENCES {_table('operation_tasks')}(id),
                    task_type TEXT NOT NULL,
                    target_type TEXT NOT NULL,
                    target_id BIGINT,
                    attempt_id BIGINT REFERENCES {_table('registration_attempts')}(id),
                    account_id BIGINT,
                    email_snapshot TEXT NOT NULL DEFAULT '',
                    requested_action TEXT NOT NULL,
                    status TEXT NOT NULL DEFAULT 'queued',
                    target_status TEXT NOT NULL DEFAULT 'unknown',
                    current_stage TEXT,
                    last_run_id BIGINT,
                    next_actions JSONB NOT NULL DEFAULT '[]'::jsonb,
                    error_category TEXT,
                    error_code TEXT,
                    error_message TEXT,
                    trigger TEXT NOT NULL DEFAULT 'manual',
                    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                    completed_at TIMESTAMPTZ,
                    data JSONB NOT NULL DEFAULT '{{}}'::jsonb,
                    UNIQUE(source_system, source_id)
                )
                """
            )
            cur.execute(
                f"""
                CREATE TABLE IF NOT EXISTS {_table('operation_runs')} (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    run_uuid TEXT NOT NULL UNIQUE,
                    task_id BIGINT NOT NULL REFERENCES {_table('operation_tasks')}(id) ON DELETE CASCADE,
                    run_no INTEGER NOT NULL,
                    source_system TEXT NOT NULL,
                    source_id TEXT NOT NULL,
                    status TEXT NOT NULL DEFAULT 'queued',
                    execution_id TEXT,
                    batch_id BIGINT REFERENCES {_table('operation_batches')}(id),
                    account_id BIGINT,
                    resource_family TEXT NOT NULL DEFAULT 'openai_interactive',
                    cancellation_token TEXT NOT NULL DEFAULT '',
                    cancel_requested_at TIMESTAMPTZ,
                    cancel_reason TEXT,
                    settling_at TIMESTAMPTZ,
                    worker_pid INTEGER,
                    heartbeat_at TIMESTAMPTZ,
                    progress_stage TEXT,
                    progress_steps JSONB NOT NULL DEFAULT '{{}}'::jsonb,
                    started_at TIMESTAMPTZ,
                    completed_at TIMESTAMPTZ,
                    duration_ms BIGINT,
                    error_category TEXT,
                    error_code TEXT,
                    error_message TEXT,
                    result_summary JSONB,
                    log_file TEXT,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                    data JSONB NOT NULL DEFAULT '{{}}'::jsonb,
                    UNIQUE(source_system, source_id),
                    UNIQUE(task_id, run_no)
                )
                """
            )
            # operation_runs 可能已经由上一版统一任务中心创建。这里全部使用
            # ADD COLUMN IF NOT EXISTS，保证开发库和已部署库都能原地升级。
            for column_sql in (
                f"batch_id BIGINT REFERENCES {_table('operation_batches')}(id)",
                "account_id BIGINT",
                "resource_family TEXT NOT NULL DEFAULT 'openai_interactive'",
                "cancellation_token TEXT NOT NULL DEFAULT ''",
                "cancel_requested_at TIMESTAMPTZ",
                "cancel_reason TEXT",
                "settling_at TIMESTAMPTZ",
            ):
                cur.execute(
                    f"ALTER TABLE {_table('operation_runs')} ADD COLUMN IF NOT EXISTS {column_sql}"
                )
            cur.execute(
                f"""
                CREATE TABLE IF NOT EXISTS {_table('operation_events')} (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    event_uuid TEXT NOT NULL UNIQUE,
                    task_id BIGINT NOT NULL REFERENCES {_table('operation_tasks')}(id) ON DELETE CASCADE,
                    run_id BIGINT REFERENCES {_table('operation_runs')}(id) ON DELETE CASCADE,
                    source_system TEXT NOT NULL,
                    source_id TEXT NOT NULL,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                    level TEXT NOT NULL DEFAULT 'INFO',
                    stage TEXT NOT NULL,
                    event_type TEXT NOT NULL DEFAULT 'progress',
                    error_category TEXT,
                    error_code TEXT,
                    message TEXT NOT NULL,
                    detail JSONB,
                    UNIQUE(source_system, source_id)
                )
                """
            )
            cur.execute(
                f"""
                CREATE TABLE IF NOT EXISTS {_table('operation_batch_items')} (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    batch_id BIGINT NOT NULL REFERENCES {_table('operation_batches')}(id) ON DELETE CASCADE,
                    task_id BIGINT NOT NULL REFERENCES {_table('operation_tasks')}(id) ON DELETE CASCADE,
                    run_id BIGINT NOT NULL REFERENCES {_table('operation_runs')}(id) ON DELETE CASCADE,
                    ordinal INTEGER NOT NULL,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                    UNIQUE(batch_id, run_id),
                    UNIQUE(batch_id, ordinal)
                )
                """
            )
            cur.execute(
                f"""
                CREATE TABLE IF NOT EXISTS {_table('account_operation_leases')} (
                    account_id BIGINT NOT NULL,
                    resource_family TEXT NOT NULL,
                    run_id BIGINT NOT NULL REFERENCES {_table('operation_runs')}(id) ON DELETE CASCADE,
                    lease_token TEXT NOT NULL UNIQUE,
                    acquired_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                    heartbeat_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                    expires_at TIMESTAMPTZ NOT NULL,
                    cancel_requested_at TIMESTAMPTZ,
                    PRIMARY KEY(account_id, resource_family)
                )
                """
            )
            cur.execute(
                f"""
                CREATE TABLE IF NOT EXISTS {_table('operation_resources')} (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    resource_uuid TEXT NOT NULL UNIQUE,
                    run_id BIGINT NOT NULL REFERENCES {_table('operation_runs')}(id) ON DELETE CASCADE,
                    resource_type TEXT NOT NULL,
                    provider TEXT NOT NULL DEFAULT '',
                    external_id TEXT NOT NULL DEFAULT '',
                    state TEXT NOT NULL DEFAULT 'acquired',
                    acquired_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                    released_at TIMESTAMPTZ,
                    detail JSONB NOT NULL DEFAULT '{{}}'::jsonb,
                    UNIQUE(run_id, resource_type, external_id)
                )
                """
            )
            indexes = (
                ("idx_operation_batches_created", "operation_batches", "created_at DESC"),
                ("idx_operation_tasks_created", "operation_tasks", "id DESC"),
                ("idx_operation_tasks_batch", "operation_tasks", "batch_id, id"),
                ("idx_operation_tasks_account", "operation_tasks", "account_id, id DESC"),
                ("idx_operation_tasks_status", "operation_tasks", "status, id DESC"),
                ("idx_operation_tasks_type", "operation_tasks", "task_type, id DESC"),
                ("idx_operation_runs_task", "operation_runs", "task_id, run_no"),
                ("idx_operation_runs_queue", "operation_runs", "status, created_at, id"),
                ("idx_operation_runs_account", "operation_runs", "account_id, id DESC"),
                ("idx_operation_events_task", "operation_events", "task_id, id"),
                ("idx_operation_events_run", "operation_events", "run_id, id"),
                ("idx_operation_batch_items_task", "operation_batch_items", "task_id, id"),
                ("idx_operation_resources_run", "operation_resources", "run_id, id"),
                ("idx_account_operation_leases_run", "account_operation_leases", "run_id"),
                ("idx_registration_attempts_account", "registration_attempts", "account_id"),
            )
            for name, table, columns in indexes:
                cur.execute(f"CREATE INDEX IF NOT EXISTS {_quote(name)} ON {_table(table)} ({columns})")
            cur.execute(
                f"""
                CREATE UNIQUE INDEX IF NOT EXISTS {_quote('uq_operation_runs_active_account_family')}
                ON {_table('operation_runs')} (account_id, resource_family)
                WHERE account_id IS NOT NULL
                  AND status IN ('queued', 'running', 'cancelling', 'settling')
                """
            )
            cur.execute(
                f"""
                UPDATE {postgres_store.qualified(record_store.ACCOUNTS.name)} account
                SET codex_credential_state=CASE
                        WHEN account.deactivated THEN 'deactivated'
                        WHEN account.codex_status='success' OR EXISTS (
                            SELECT 1 FROM {postgres_store.qualified(record_store.CODEX_CREDENTIALS.name)} credential
                            WHERE credential.archived IS FALSE
                              AND LOWER(COALESCE(credential.email, ''))=LOWER(account.email)
                        ) THEN 'valid'
                        ELSE 'none'
                    END,
                    codex_execution_status=COALESCE(account.codex_execution_status, 'empty'),
                    codex_last_run_status=COALESCE(
                        account.codex_last_run_status,
                        CASE
                            WHEN account.codex_status='success' THEN 'success'
                            WHEN account.codex_status IN ('failed','stopped','deactivated','interrupted') THEN account.codex_status
                            ELSE NULL
                        END
                    )
                WHERE account.codex_credential_state IS NULL
                   OR account.codex_execution_status IS NULL
                """
            )
        _READY_KEY = ready_key


def _account_extra(account: dict | None) -> dict:
    raw = (account or {}).get("extra_json") or {}
    if isinstance(raw, str):
        try:
            raw = json.loads(raw)
        except (TypeError, ValueError):
            raw = {}
    return dict(raw) if isinstance(raw, dict) else {}


def _account_state(account: dict | None) -> dict[str, str]:
    if not account:
        return {
            "checkpoint": "unknown", "remote_identity_state": "unknown",
            "remote_account_state": "unknown", "local_account_state": "missing",
            "target_status": "not_created",
        }
    extra = _account_extra(account)
    checkpoint = str(extra.get("registration_checkpoint") or "unknown")
    has_token = bool(str(account.get("access_token") or "").strip())
    if has_token:
        return {
            "checkpoint": checkpoint if checkpoint != "unknown" else "registered",
            "remote_identity_state": "verified", "remote_account_state": "created",
            "local_account_state": "saved", "target_status": "account_available",
        }
    if checkpoint == "email_verification_pending":
        return {
            "checkpoint": checkpoint, "remote_identity_state": "created_unverified",
            "remote_account_state": "pending_profile", "local_account_state": "checkpoint_saved",
            "target_status": "email_verification_pending",
        }
    return {
        "checkpoint": checkpoint, "remote_identity_state": "unknown",
        "remote_account_state": "unknown", "local_account_state": "checkpoint_saved",
        "target_status": "attention_required",
    }


def _error_fields(message: Any, *, stage: str = "", task_type: str = "") -> tuple[str | None, str | None, str | None]:
    raw = _text(message, 1600).strip()
    info = classify_task_error(raw, stage=stage, task_type=task_type) if raw else None
    return (
        str((info or {}).get("source") or "") or None,
        str((info or {}).get("code") or "") or None,
        raw or None,
    )


def _status(value: Any) -> str:
    status = str(value or "queued").strip().lower()
    return "queued" if status == "pending" else status


def _duration(started: Any, completed: Any, explicit: Any = None) -> int | None:
    if explicit not in (None, ""):
        try:
            return max(0, int(explicit))
        except (TypeError, ValueError):
            pass
    if not started or not completed:
        return None
    try:
        left = datetime.fromisoformat(str(started).replace("Z", "+00:00"))
        right = datetime.fromisoformat(str(completed).replace("Z", "+00:00"))
        return max(0, int((right - left).total_seconds() * 1000))
    except (TypeError, ValueError):
        return None


def _upsert_batch(
    cur,
    *,
    source_system: str,
    source_id: str,
    batch_type: str,
    title: str,
    requested_count: int,
    created_by: str,
    created_at: Any,
    completed_at: Any = None,
    data: dict | None = None,
) -> int:
    cur.execute(
        f"""
        INSERT INTO {_table('operation_batches')} (
            batch_uuid, source_system, source_id, batch_type, title, requested_count,
            created_by, created_at, completed_at, data
        ) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s::jsonb)
        ON CONFLICT (source_system, source_id) DO UPDATE SET
            batch_type=EXCLUDED.batch_type, title=EXCLUDED.title,
            requested_count=GREATEST({_table('operation_batches')}.requested_count, EXCLUDED.requested_count),
            completed_at=COALESCE(EXCLUDED.completed_at, {_table('operation_batches')}.completed_at),
            data={_table('operation_batches')}.data || EXCLUDED.data
        RETURNING id
        """,
        (
            _uuid("batch", f"{source_system}:{source_id}"), source_system, source_id,
            batch_type, _text(title, 240), max(0, int(requested_count or 0)), created_by,
            created_at or _now(), completed_at, _json(data or {}),
        ),
    )
    return int(cur.fetchone()["id"])


def _upsert_attempt(cur, *, root_job_id: int, job: dict, account: dict | None) -> int:
    state = _account_state(account)
    cur.execute(
        f"""
        INSERT INTO {_table('registration_attempts')} (
            attempt_uuid, source_root_job_id, email_snapshot, account_id, checkpoint,
            remote_identity_state, remote_account_state, local_account_state, target_status,
            created_at, updated_at, completed_at, data
        ) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s::jsonb)
        ON CONFLICT (source_root_job_id) DO UPDATE SET
            email_snapshot=CASE WHEN EXCLUDED.email_snapshot <> '' THEN EXCLUDED.email_snapshot
                ELSE {_table('registration_attempts')}.email_snapshot END,
            account_id=COALESCE(EXCLUDED.account_id, {_table('registration_attempts')}.account_id),
            checkpoint=EXCLUDED.checkpoint,
            remote_identity_state=EXCLUDED.remote_identity_state,
            remote_account_state=EXCLUDED.remote_account_state,
            local_account_state=EXCLUDED.local_account_state,
            target_status=EXCLUDED.target_status,
            updated_at=EXCLUDED.updated_at,
            completed_at=COALESCE(EXCLUDED.completed_at, {_table('registration_attempts')}.completed_at),
            data={_table('registration_attempts')}.data || EXCLUDED.data
        RETURNING id
        """,
        (
            _uuid("attempt", root_job_id), root_job_id,
            str((account or {}).get("email") or job.get("email") or "")[:320],
            int(account["id"]) if account and account.get("id") is not None else None,
            state["checkpoint"], state["remote_identity_state"], state["remote_account_state"],
            state["local_account_state"], state["target_status"], job.get("created_at") or _now(),
            job.get("updated_at") or job.get("completed_at") or _now(),
            job.get("completed_at") if state["target_status"] == "account_available" else None,
            _json({"legacy_root_job_id": root_job_id}),
        ),
    )
    return int(cur.fetchone()["id"])


def _registration_task_type(job: dict) -> str:
    value = str(job.get("job_type") or "registration").strip().lower()
    return value if value in {"registration", "registration_resume", "codex_retry", "twofa_retry"} else "registration"


def _next_registration_actions(job: dict, account: dict | None, target_status: str) -> list[dict[str, Any]]:
    if _status(job.get("status")) not in _TERMINAL_STATUSES:
        return []
    source_job_id = int(job.get("id") or 0)
    if target_status == "email_verification_pending":
        return [{"action": "registration_resume", "label": "继续邮箱验证", "source_job_id": source_job_id}]
    if not account:
        return [{"action": "registration_retry", "label": "重新执行注册", "source_job_id": source_job_id}]
    if str(account.get("codex_status") or "") != "success":
        return [{"action": "codex_retry", "label": "补跑 Codex", "source_job_id": source_job_id}]
    extra = _account_extra(account)
    missing_setup = (
        not str(extra.get("account_password") or extra.get("login_password") or "").strip()
        or not str(account.get("totp_secret") or "").strip()
        or bool(extra.get("totp_setup_pending"))
        or str(account.get("plan_check_status") or "").lower() != "success"
    )
    if missing_setup:
        return [{"action": "twofa_retry", "label": "补齐账号配置", "source_job_id": source_job_id}]
    return []


def _lookup_task(cur, source_system: str, source_id: str) -> int | None:
    cur.execute(
        f"SELECT id FROM {_table('operation_tasks')} WHERE source_system=%s AND source_id=%s",
        (source_system, source_id),
    )
    row = cur.fetchone()
    return int(row["id"]) if row else None


def _upsert_registration_job(cur, job: dict, accounts_by_id: dict[int, dict], accounts_by_email: dict[str, dict]) -> int:
    job_id = int(job["id"])
    root_job_id = int(job.get("root_job_id") or job_id)
    task_type = _registration_task_type(job)
    task_source_id = f"{root_job_id}:{task_type}"
    account = None
    if job.get("account_id") is not None:
        account = accounts_by_id.get(int(job["account_id"]))
    if account is None and job.get("email"):
        account = accounts_by_email.get(str(job.get("email") or "").strip().lower())
    attempt_id = _upsert_attempt(cur, root_job_id=root_job_id, job=job, account=account)
    state = _account_state(account)
    batch_id = None
    legacy_batch_id = str(job.get("batch_id") or "").strip()
    if legacy_batch_id:
        batch_id = _upsert_batch(
            cur,
            source_system="registration_batches",
            source_id=legacy_batch_id,
            batch_type="registration" if task_type == "registration" else "retry",
            title="注册批次" if task_type == "registration" else "注册补跑批次",
            requested_count=int(job.get("batch_size") or 1),
            created_by="webui",
            created_at=job.get("created_at"),
            data={"legacy_batch_id": legacy_batch_id, "workers": job.get("batch_workers")},
        )
    parent_task_id = None
    if task_type != "registration":
        parent_task_id = _lookup_task(cur, "registration_chains", f"{root_job_id}:registration")
    error_category, error_code, error_message = _error_fields(
        job.get("error_message"), stage=str(job.get("progress_stage") or ""), task_type=task_type,
    )
    source_system = "registration_chains"
    status = _status(job.get("status"))
    next_actions = _next_registration_actions(job, account, state["target_status"])
    cur.execute(
        f"""
        INSERT INTO {_table('operation_tasks')} (
            task_uuid, source_system, source_id, batch_id, parent_task_id, task_type,
            target_type, target_id, attempt_id, account_id, email_snapshot, requested_action,
            status, target_status, current_stage, next_actions, error_category, error_code,
            error_message, trigger, created_at, updated_at, completed_at, data
        ) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s::jsonb,%s,%s,%s,%s,%s,%s,%s,%s::jsonb)
        ON CONFLICT (source_system, source_id) DO UPDATE SET
            batch_id=COALESCE(EXCLUDED.batch_id, {_table('operation_tasks')}.batch_id),
            parent_task_id=COALESCE(EXCLUDED.parent_task_id, {_table('operation_tasks')}.parent_task_id),
            attempt_id=EXCLUDED.attempt_id,
            account_id=COALESCE(EXCLUDED.account_id, {_table('operation_tasks')}.account_id),
            email_snapshot=CASE WHEN EXCLUDED.email_snapshot <> '' THEN EXCLUDED.email_snapshot
                ELSE {_table('operation_tasks')}.email_snapshot END,
            status=EXCLUDED.status, target_status=EXCLUDED.target_status,
            current_stage=EXCLUDED.current_stage, next_actions=EXCLUDED.next_actions,
            error_category=EXCLUDED.error_category, error_code=EXCLUDED.error_code,
            error_message=EXCLUDED.error_message, updated_at=EXCLUDED.updated_at,
            completed_at=EXCLUDED.completed_at,
            data={_table('operation_tasks')}.data || EXCLUDED.data
        RETURNING id
        """,
        (
            _uuid("task", f"{source_system}:{task_source_id}"), source_system, task_source_id,
            batch_id, parent_task_id, task_type,
            "account" if task_type in {"codex_retry", "twofa_retry"} and account else "registration_attempt",
            int(account["id"]) if account and task_type in {"codex_retry", "twofa_retry"} else attempt_id,
            attempt_id, int(account["id"]) if account else None,
            str((account or {}).get("email") or job.get("email") or "")[:320], task_type,
            status, state["target_status"], normalize_stage(job.get("progress_stage")), _json(next_actions),
            error_category, error_code, error_message,
            "manual_retry" if job.get("parent_job_id") else "manual",
            job.get("created_at") or _now(), job.get("updated_at") or job.get("completed_at") or _now(),
            job.get("completed_at") if status in _TERMINAL_STATUSES else None,
            _json({"legacy_root_job_id": root_job_id, "latest_legacy_job_id": job_id}),
        ),
    )
    task_id = int(cur.fetchone()["id"])
    if task_type == "registration":
        cur.execute(
            f"UPDATE {_table('operation_tasks')} SET root_task_id=id WHERE id=%s AND root_task_id IS NULL",
            (task_id,),
        )
        cur.execute(
            f"UPDATE {_table('registration_attempts')} SET root_task_id=%s WHERE id=%s",
            (task_id, attempt_id),
        )
    else:
        root_task_id = parent_task_id or task_id
        cur.execute(
            f"UPDATE {_table('operation_tasks')} SET root_task_id=%s WHERE id=%s",
            (root_task_id, task_id),
        )
    retry_attempt = int(job.get("retry_attempt") or 0)
    run_no = max(1, retry_attempt + 1)
    progress_steps = job.get("progress_steps") if isinstance(job.get("progress_steps"), dict) else {}
    cur.execute(
        f"SELECT id FROM {_table('operation_runs')} WHERE source_system='registration_jobs' AND source_id=%s",
        (str(job_id),),
    )
    existing_run = cur.fetchone()
    if existing_run:
        run_no_clause = "run_no=operation_runs.run_no,"
    else:
        cur.execute(f"SELECT COALESCE(MAX(run_no),0)+1 AS n FROM {_table('operation_runs')} WHERE task_id=%s", (task_id,))
        run_no = max(run_no, int(cur.fetchone()["n"]))
        run_no_clause = "run_no=EXCLUDED.run_no,"
    cur.execute(
        f"""
        INSERT INTO {_table('operation_runs')} (
            run_uuid, task_id, run_no, source_system, source_id, status, execution_id,
            progress_stage, progress_steps, started_at, completed_at, duration_ms,
            error_category, error_code, error_message, result_summary, log_file, created_at, data
        ) VALUES (%s,%s,%s,'registration_jobs',%s,%s,%s,%s,%s::jsonb,%s,%s,%s,%s,%s,%s,%s::jsonb,%s,%s,%s::jsonb)
        ON CONFLICT (source_system, source_id) DO UPDATE SET
            task_id=EXCLUDED.task_id, {run_no_clause} status=EXCLUDED.status,
            progress_stage=EXCLUDED.progress_stage, progress_steps=EXCLUDED.progress_steps,
            started_at=EXCLUDED.started_at, completed_at=EXCLUDED.completed_at,
            duration_ms=EXCLUDED.duration_ms, error_category=EXCLUDED.error_category,
            error_code=EXCLUDED.error_code, error_message=EXCLUDED.error_message,
            result_summary=EXCLUDED.result_summary, log_file=EXCLUDED.log_file,
            data={_table('operation_runs')}.data || EXCLUDED.data
        RETURNING id
        """,
        (
            _uuid("run", f"registration_jobs:{job_id}"), task_id, run_no, str(job_id), status,
            str(job.get("job_uuid") or "") or None, normalize_stage(job.get("progress_stage")),
            _json(progress_steps), job.get("started_at"), job.get("completed_at"),
            _duration(job.get("started_at"), job.get("completed_at")), error_category, error_code,
            error_message, _json({"account_id": (account or {}).get("id"), "retry_action": job.get("retry_action")}),
            str(job.get("log_file") or "") or None, job.get("created_at") or _now(),
            _json({"legacy_job_id": job_id, "parent_job_id": job.get("parent_job_id")}),
        ),
    )
    run_id = int(cur.fetchone()["id"])
    for raw_stage, raw_step in progress_steps.items():
        step = raw_step if isinstance(raw_step, dict) else {}
        stage = normalize_stage(raw_stage)
        state_value = str(step.get("state") or "pending")
        level = "ERROR" if state_value in {"failed", "stopped"} else "INFO"
        category, code, _ = _error_fields(
            step.get("detail") if level == "ERROR" else None, stage=stage, task_type=task_type,
        )
        event_source_id = f"{job_id}:stage:{raw_stage}"
        cur.execute(
            f"""
            INSERT INTO {_table('operation_events')} (
                event_uuid, task_id, run_id, source_system, source_id, created_at, level,
                stage, event_type, error_category, error_code, message, detail
            ) VALUES (%s,%s,%s,'registration_progress',%s,%s,%s,%s,%s,%s,%s,%s,%s::jsonb)
            ON CONFLICT (source_system, source_id) DO UPDATE SET
                task_id=EXCLUDED.task_id, run_id=EXCLUDED.run_id, created_at=EXCLUDED.created_at,
                level=EXCLUDED.level, stage=EXCLUDED.stage, event_type=EXCLUDED.event_type,
                error_category=EXCLUDED.error_category, error_code=EXCLUDED.error_code,
                message=EXCLUDED.message, detail=EXCLUDED.detail
            """,
            (
                _uuid("event", f"registration_progress:{event_source_id}"), task_id, run_id,
                event_source_id, step.get("completed_at") or step.get("started_at") or job.get("updated_at") or _now(),
                level, stage, f"stage.{state_value}", category, code,
                _text(step.get("detail") or state_value, 1200),
                _json({"state": state_value, "started_at": step.get("started_at"), "completed_at": step.get("completed_at")}),
            ),
        )
    cur.execute(
        f"""
        SELECT id, status, progress_stage, error_category, error_code, error_message, completed_at
        FROM {_table('operation_runs')} WHERE task_id=%s ORDER BY run_no DESC, id DESC LIMIT 1
        """,
        (task_id,),
    )
    latest = cur.fetchone()
    cur.execute(
        f"""
        UPDATE {_table('operation_tasks')} SET last_run_id=%s, status=%s, current_stage=%s,
            error_category=%s, error_code=%s, error_message=%s,
            completed_at=%s, updated_at=now(), next_actions=%s::jsonb
        WHERE id=%s
        """,
        (
            latest["id"], latest["status"], latest["progress_stage"], latest["error_category"],
            latest["error_code"], latest["error_message"], latest["completed_at"],
            _json(_next_registration_actions(job, account, state["target_status"])), task_id,
        ),
    )
    return task_id


def _upsert_account_batch(cur, batch: dict) -> int:
    return _upsert_batch(
        cur,
        source_system="account_action_batches",
        source_id=str(batch["id"]),
        batch_type="account_action",
        title=str(batch.get("action_type") or "账号操作批次"),
        requested_count=int(batch.get("total_count") or 0),
        created_by=str(batch.get("trigger") or "manual"),
        created_at=batch.get("created_at"),
        completed_at=batch.get("completed_at"),
        data={"legacy_action_type": batch.get("action_type")},
    )


def _upsert_account_task(
    cur,
    task: dict,
    batch_map: dict[str, int],
    accounts_by_id: dict[int, dict] | None = None,
) -> int:
    legacy_id = int(task["id"])
    task_type = str(task.get("task_type") or "unknown")
    status = _status(task.get("status"))
    category, code, error = _error_fields(task.get("error"), stage="complete", task_type=task_type)
    batch_id = batch_map.get(str(task.get("batch_id") or ""))
    account_id = int(task["account_id"]) if task.get("account_id") is not None else None
    account = (accounts_by_id or {}).get(account_id) if account_id is not None else None
    account_state = _account_state(account)
    target_status = "deactivated" if status == "deactivated" else account_state["target_status"]
    next_actions: list[dict[str, Any]] = []
    if target_status == "email_verification_pending" and account_id is not None:
        cur.execute(
            f"""
            SELECT next_actions FROM {_table('operation_tasks')}
            WHERE account_id=%s AND task_type='registration'
              AND target_status='email_verification_pending'
            ORDER BY id DESC LIMIT 1
            """,
            (account_id,),
        )
        registration_task = cur.fetchone()
        if registration_task:
            next_actions = _decode(registration_task["next_actions"]) or []
    elif status != "success":
        next_actions = [{"action": "retry", "label": "重新执行", "source_task_id": legacy_id}]
    source_id = str(legacy_id)
    cur.execute(
        f"""
        INSERT INTO {_table('operation_tasks')} (
            task_uuid, source_system, source_id, batch_id, task_type, target_type, target_id,
            account_id, email_snapshot, requested_action, status, target_status, current_stage,
            next_actions, error_category, error_code, error_message, trigger,
            created_at, updated_at, completed_at, data
        ) VALUES (%s,'account_action_tasks',%s,%s,%s,'account',%s,%s,%s,%s,%s,%s,%s,%s::jsonb,%s,%s,%s,%s,%s,%s,%s,%s::jsonb)
        ON CONFLICT (source_system, source_id) DO UPDATE SET
            batch_id=COALESCE(EXCLUDED.batch_id, {_table('operation_tasks')}.batch_id),
            task_type=EXCLUDED.task_type, account_id=EXCLUDED.account_id,
            target_id=EXCLUDED.target_id, email_snapshot=EXCLUDED.email_snapshot,
            status=EXCLUDED.status, target_status=EXCLUDED.target_status,
            current_stage=EXCLUDED.current_stage, next_actions=EXCLUDED.next_actions,
            error_category=EXCLUDED.error_category, error_code=EXCLUDED.error_code,
            error_message=EXCLUDED.error_message, updated_at=EXCLUDED.updated_at,
            completed_at=EXCLUDED.completed_at,
            data={_table('operation_tasks')}.data || EXCLUDED.data
        RETURNING id
        """,
        (
            _uuid("task", f"account_action_tasks:{legacy_id}"), source_id, batch_id, task_type,
            account_id, account_id, str(task.get("email_snapshot") or "")[:320], task_type,
            status, target_status, "complete" if status in _TERMINAL_STATUSES else status,
            _json(next_actions),
            category, code, error, str(task.get("trigger") or "manual"),
            task.get("queued_at") or _now(), task.get("finished_at") or task.get("started_at") or task.get("queued_at") or _now(),
            task.get("finished_at"), _json({"legacy_account_task_id": legacy_id}),
        ),
    )
    operation_task_id = int(cur.fetchone()["id"])
    cur.execute(
        f"UPDATE {_table('operation_tasks')} SET root_task_id=id WHERE id=%s AND root_task_id IS NULL",
        (operation_task_id,),
    )
    cur.execute(
        f"""
        INSERT INTO {_table('operation_runs')} (
            run_uuid, task_id, run_no, source_system, source_id, status, progress_stage,
            started_at, completed_at, duration_ms, error_category, error_code, error_message,
            result_summary, created_at, data
        ) VALUES (%s,%s,1,'account_action_tasks',%s,%s,%s,%s,%s,%s,%s,%s,%s,%s::jsonb,%s,%s::jsonb)
        ON CONFLICT (source_system, source_id) DO UPDATE SET
            task_id=EXCLUDED.task_id, status=EXCLUDED.status, progress_stage=EXCLUDED.progress_stage,
            started_at=EXCLUDED.started_at, completed_at=EXCLUDED.completed_at,
            duration_ms=EXCLUDED.duration_ms, error_category=EXCLUDED.error_category,
            error_code=EXCLUDED.error_code, error_message=EXCLUDED.error_message,
            result_summary=EXCLUDED.result_summary, data={_table('operation_runs')}.data || EXCLUDED.data
        RETURNING id
        """,
        (
            _uuid("run", f"account_action_tasks:{legacy_id}"), operation_task_id, source_id, status,
            "complete" if status in _TERMINAL_STATUSES else status,
            task.get("started_at"), task.get("finished_at"), task.get("duration_ms"),
            category, code, error, _json(task.get("result_summary") or {}),
            task.get("queued_at") or _now(),
            _json({
                "validation_method": task.get("validation_method"),
                "network_route": task.get("network_route"),
                "proxy_mode": task.get("proxy_mode"),
                "proxy_provider": task.get("proxy_provider"),
                "proxy_region": task.get("proxy_region"),
                "proxy_used": task.get("proxy_used"),
            }),
        ),
    )
    run_id = int(cur.fetchone()["id"])
    cur.execute(
        f"UPDATE {_table('operation_tasks')} SET last_run_id=%s WHERE id=%s",
        (run_id, operation_task_id),
    )
    return operation_task_id


def _upsert_account_event(cur, event: dict, task_map: dict[int, int]) -> None:
    legacy_task_id = int(event["task_id"])
    operation_task_id = task_map.get(legacy_task_id)
    if not operation_task_id:
        return
    cur.execute(
        f"SELECT id FROM {_table('operation_runs')} WHERE source_system='account_action_tasks' AND source_id=%s",
        (str(legacy_task_id),),
    )
    run = cur.fetchone()
    level = str(event.get("level") or "INFO").upper()
    raw_stage = str(event.get("stage") or "event")
    stage = normalize_stage(raw_stage)
    detail = event.get("detail") if isinstance(event.get("detail"), dict) else {}
    explicit_state = normalize_step_state(detail.get("step_state"))
    if explicit_state is not None:
        event_type = f"stage.{explicit_state}"
    elif level == "ERROR":
        event_type = "stage.failed"
    else:
        message = str(event.get("message") or "")
        lowered = message.lower()
        if any(marker in message for marker in ("跳过", "无需", "暂时无法")):
            event_type = "stage.skipped"
        elif raw_stage.endswith("_result"):
            event_type = (
                "stage.failed"
                if level == "WARNING" or any(marker in message for marker in ("失败", "异常", "未完成"))
                else "stage.success"
            )
        elif raw_stage == "complete":
            event_type = "stage.success"
        elif any(marker in message for marker in ("已分配", "已启用", "已完成", "已写回", "已保存")):
            event_type = "stage.success"
        else:
            event_type = "stage.running"
    category, code, _ = _error_fields(
        event.get("message") if level == "ERROR" else None, stage=stage,
    )
    source_id = str(event["id"])
    cur.execute(
        f"""
        INSERT INTO {_table('operation_events')} (
            event_uuid, task_id, run_id, source_system, source_id, created_at, level,
            stage, event_type, error_category, error_code, message, detail
        ) VALUES (%s,%s,%s,'account_action_events',%s,%s,%s,%s,%s,%s,%s,%s,%s::jsonb)
        ON CONFLICT (source_system, source_id) DO UPDATE SET
            task_id=EXCLUDED.task_id, run_id=EXCLUDED.run_id, created_at=EXCLUDED.created_at,
            level=EXCLUDED.level, stage=EXCLUDED.stage, event_type=EXCLUDED.event_type,
            error_category=EXCLUDED.error_category,
            error_code=EXCLUDED.error_code, message=EXCLUDED.message, detail=EXCLUDED.detail
        """,
        (
            _uuid("event", f"account_action_events:{source_id}"), operation_task_id,
            int(run["id"]) if run else None, source_id, event.get("created_at") or _now(),
            level, stage, event_type, category, code, _text(event.get("message"), 1600),
            _json(detail),
        ),
    )


def _refresh_batches(cur) -> None:
    cur.execute(f"SELECT id, skipped_count FROM {_table('operation_batches')}")
    for raw in cur.fetchall():
        batch_id = int(raw["id"])
        skipped = int(raw.get("skipped_count") or 0)
        cur.execute(
            f"SELECT status, COUNT(*) AS n FROM {_table('operation_tasks')} WHERE batch_id=%s GROUP BY status",
            (batch_id,),
        )
        counts = {str(row["status"]): int(row["n"]) for row in cur.fetchall()}
        queued = counts.get("queued", 0)
        running = (
            counts.get("running", 0) + counts.get("stopping", 0)
            + counts.get("cancelling", 0) + counts.get("settling", 0)
            + counts.get("waiting", 0)
        )
        success = counts.get("success", 0)
        partial = counts.get("partial_success", 0)
        failed = counts.get("failed", 0) + counts.get("deactivated", 0) + counts.get("unsupported", 0)
        attention = counts.get("attention_required", 0) + counts.get("interrupted", 0)
        stopped = counts.get("stopped", 0)
        cancelled = counts.get("cancelled", 0)
        if running:
            status = "running"
            completed_at = None
        elif queued:
            status = "queued"
            completed_at = None
        elif failed or attention or skipped:
            status = "partial_success" if success or partial else "failed"
            completed_at = _now()
        elif partial:
            status = "partial_success"
            completed_at = _now()
        elif success:
            status = "success"
            completed_at = _now()
        elif stopped or cancelled:
            status = "stopped"
            completed_at = _now()
        else:
            status = "queued"
            completed_at = None
        cur.execute(
            f"""
            UPDATE {_table('operation_batches')} SET status=%s, queued_count=%s,
                running_count=%s, success_count=%s, partial_count=%s, failed_count=%s,
                attention_count=%s, stopped_count=%s, cancelled_count=%s,
                completed_at=COALESCE(%s, completed_at)
            WHERE id=%s
            """,
            (status, queued, running, success, partial, failed, attention, stopped, cancelled, completed_at, batch_id),
        )


def reconcile_all() -> dict[str, int]:
    """从两套旧表幂等回填统一模型；不会删除旧数据，也不会改账号业务字段。"""
    init()
    record_store.init()
    with _LOCK, _connect() as conn, conn.cursor() as cur:
        cur.execute(f"SELECT * FROM {postgres_store.qualified('registered_accounts')} ORDER BY id")
        accounts = [record_store.merge_row(record_store.ACCOUNTS, dict(row)) or {} for row in cur.fetchall()]
        accounts_by_id = {int(row["id"]): row for row in accounts if row.get("id") is not None}
        accounts_by_email = {
            str(row.get("email") or "").strip().lower(): row for row in accounts if str(row.get("email") or "").strip()
        }
        cur.execute(f"SELECT * FROM {postgres_store.qualified('registration_jobs')} ORDER BY id")
        jobs = [record_store.merge_row(record_store.JOBS, dict(row)) or {} for row in cur.fetchall()]
        for job in jobs:
            _upsert_registration_job(cur, job, accounts_by_id, accounts_by_email)

        cur.execute(f"SELECT * FROM {_table('account_action_batches')} ORDER BY created_at, id")
        account_batches = [dict(row) for row in cur.fetchall()]
        batch_map = {str(row["id"]): _upsert_account_batch(cur, row) for row in account_batches}
        cur.execute(f"SELECT * FROM {_table('account_action_tasks')} ORDER BY id")
        account_tasks = [dict(row) for row in cur.fetchall()]
        task_map = {
            int(row["id"]): _upsert_account_task(cur, row, batch_map, accounts_by_id)
            for row in account_tasks
        }
        cur.execute(f"SELECT * FROM {_table('account_action_events')} ORDER BY id")
        account_events = [dict(row) for row in cur.fetchall()]
        for event in account_events:
            _upsert_account_event(cur, event, task_map)
        _refresh_batches(cur)
        return {
            "registration_jobs": len(jobs),
            "account_action_batches": len(account_batches),
            "account_action_tasks": len(account_tasks),
            "account_action_events": len(account_events),
        }


def sync_registration_job(job_id: int) -> None:
    """同步一条注册执行。调用方可在每次旧表更新后调用，失败应显式暴露。"""
    init()
    record_store.init()
    job = record_store.get_row(record_store.JOBS, int(job_id))
    if not job:
        mark_registration_jobs_deleted([int(job_id)])
        return
    account = None
    if job.get("account_id") is not None:
        account = record_store.get_row(record_store.ACCOUNTS, int(job["account_id"]))
    if account is None and job.get("email"):
        rows = record_store.list_rows(
            record_store.ACCOUNTS,
            where="lower(email)=lower(%s)", params=(str(job["email"]),), order_by="id DESC", limit=1,
        )
        account = rows[0] if rows else None
    accounts_by_id = {int(account["id"]): account} if account and account.get("id") is not None else {}
    accounts_by_email = {
        str(account.get("email") or "").strip().lower(): account
    } if account else {}
    with _connect() as conn, conn.cursor() as cur:
        _upsert_registration_job(cur, job, accounts_by_id, accounts_by_email)
        _refresh_batches(cur)


def sync_account_task(task_id: int) -> None:
    init()
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(f"SELECT * FROM {_table('account_action_batches')}")
        batch_map = {str(row["id"]): _upsert_account_batch(cur, dict(row)) for row in cur.fetchall()}
        cur.execute(f"SELECT * FROM {_table('account_action_tasks')} WHERE id=%s", (int(task_id),))
        task = cur.fetchone()
        if not task:
            return
        accounts_by_id: dict[int, dict] = {}
        if task.get("account_id") is not None:
            cur.execute(
                f"SELECT * FROM {postgres_store.qualified('registered_accounts')} WHERE id=%s",
                (int(task["account_id"]),),
            )
            raw_account = cur.fetchone()
            if raw_account:
                account = record_store.merge_row(record_store.ACCOUNTS, dict(raw_account)) or {}
                accounts_by_id[int(account["id"])] = account
        operation_task_id = _upsert_account_task(cur, dict(task), batch_map, accounts_by_id)
        cur.execute(f"SELECT * FROM {_table('account_action_events')} WHERE task_id=%s ORDER BY id", (int(task_id),))
        task_map = {int(task_id): operation_task_id}
        for event in cur.fetchall():
            _upsert_account_event(cur, dict(event), task_map)
        _refresh_batches(cur)


def mark_registration_jobs_deleted(job_ids: Iterable[int]) -> None:
    ids = [str(int(value)) for value in job_ids]
    if not ids:
        return
    init()
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            f"""
            UPDATE {_table('operation_runs')} SET data=data || '{{"source_deleted":true}}'::jsonb
            WHERE source_system='registration_jobs' AND source_id = ANY(%s)
            """,
            (ids,),
        )


def list_batches(*, limit: int = 50) -> list[dict]:
    init()
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            f"SELECT * FROM {_table('operation_batches')} ORDER BY created_at DESC, id DESC LIMIT %s",
            (max(1, min(200, int(limit or 50))),),
        )
        return [_row(dict(row)) or {} for row in cur.fetchall()]


def list_tasks(
    *, page: int = 1, page_size: int = 50, task_type: str = "", status: str = "",
    source: str = "", q: str = "", batch_id: int | None = None,
) -> dict:
    init()
    page = max(1, int(page or 1))
    page_size = max(1, min(200, int(page_size or 50)))
    where: list[str] = []
    params: list[Any] = []
    if task_type:
        where.append("t.task_type=%s")
        params.append(str(task_type))
    if status:
        where.append("t.status=%s")
        params.append(str(status))
    if source:
        where.append("t.source_system=%s")
        params.append(str(source))
    if batch_id:
        where.append("t.batch_id=%s")
        params.append(int(batch_id))
    if q:
        needle = f"%{str(q).strip()}%"
        where.append("(t.email_snapshot ILIKE %s OR CAST(t.account_id AS TEXT) ILIKE %s OR CAST(t.id AS TEXT) ILIKE %s OR t.error_message ILIKE %s)")
        params.extend((needle, needle, needle, needle))
    clause = f" WHERE {' AND '.join(where)}" if where else ""
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(f"SELECT COUNT(*) AS n FROM {_table('operation_tasks')} t{clause}", params)
        total = int(cur.fetchone()["n"])
        cur.execute(
            f"""
            SELECT t.*, b.batch_uuid, b.title AS batch_title, b.batch_type,
                   r.run_no AS last_run_no, r.duration_ms, r.result_summary,
                   r.source_system AS run_source_system, r.source_id AS run_source_id,
                   (SELECT COUNT(*) FROM {_table('operation_runs')} rr WHERE rr.task_id=t.id) AS run_count
            FROM {_table('operation_tasks')} t
            LEFT JOIN {_table('operation_batches')} b ON b.id=t.batch_id
            LEFT JOIN {_table('operation_runs')} r ON r.id=t.last_run_id
            {clause}
            ORDER BY t.updated_at DESC, t.id DESC LIMIT %s OFFSET %s
            """,
            (*params, page_size, (page - 1) * page_size),
        )
        items = [_row(dict(row)) or {} for row in cur.fetchall()]
    return {"ok": True, "items": items, "total": total, "page": page, "page_size": page_size}


def get_task(task_id: int) -> dict | None:
    init()
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            f"""
            SELECT t.*, b.batch_uuid, b.title AS batch_title, b.batch_type
            FROM {_table('operation_tasks')} t
            LEFT JOIN {_table('operation_batches')} b ON b.id=t.batch_id
            WHERE t.id=%s
            """,
            (int(task_id),),
        )
        task = cur.fetchone()
        if not task:
            return None
        cur.execute(f"SELECT * FROM {_table('operation_runs')} WHERE task_id=%s ORDER BY run_no, id", (int(task_id),))
        runs = [_row(dict(row)) or {} for row in cur.fetchall()]
        cur.execute(
            f"""
            SELECT e.*, r.run_no
            FROM {_table('operation_events')} e
            LEFT JOIN {_table('operation_runs')} r ON r.id=e.run_id
            WHERE e.task_id=%s ORDER BY e.created_at, e.id
            """,
            (int(task_id),),
        )
        events = [_row(dict(row)) or {} for row in cur.fetchall()]
        cur.execute(
            f"""
            SELECT resource.*
            FROM {_table('operation_resources')} resource
            JOIN {_table('operation_runs')} run ON run.id=resource.run_id
            WHERE run.task_id=%s ORDER BY resource.acquired_at, resource.id
            """,
            (int(task_id),),
        )
        resources = [_row(dict(row)) or {} for row in cur.fetchall()]
        attempt = None
        if task.get("attempt_id"):
            cur.execute(f"SELECT * FROM {_table('registration_attempts')} WHERE id=%s", (int(task["attempt_id"]),))
            raw_attempt = cur.fetchone()
            attempt = _row(dict(raw_attempt)) if raw_attempt else None
        parent = None
        if task.get("parent_task_id"):
            cur.execute(
                f"SELECT id, task_uuid, task_type, status, target_status FROM {_table('operation_tasks')} WHERE id=%s",
                (int(task["parent_task_id"]),),
            )
            raw_parent = cur.fetchone()
            parent = _row(dict(raw_parent)) if raw_parent else None
    result = _row(dict(task)) or {}
    result.update({
        "runs": runs,
        "events": events,
        "resources": resources,
        "attempt": attempt,
        "parent": parent,
        "flow": flow_for(result.get("task_type")),
    })
    return result


def find_task_by_source(source_system: str, source_id: str) -> dict | None:
    init()
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            f"SELECT * FROM {_table('operation_tasks')} WHERE source_system=%s AND source_id=%s",
            (str(source_system), str(source_id)),
        )
        raw = cur.fetchone()
        return _row(dict(raw)) if raw else None


# ============================================================
# 原生运行时写模型
# ============================================================

def create_runtime_batch(
    *, batch_type: str, title: str, requested_count: int, trigger: str = "manual",
    data: dict | None = None,
) -> dict:
    """创建真正参与调度的批次；批次只持有 run 引用，不预占账号资源。"""
    init()
    batch_uuid = uuid.uuid4().hex
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            f"""
            INSERT INTO {_table('operation_batches')} (
                batch_uuid, source_system, source_id, batch_type, title, status,
                requested_count, created_by, data
            ) VALUES (%s, 'native_operations', %s, %s, %s, 'queued', %s, %s, %s::jsonb)
            RETURNING *
            """,
            (
                batch_uuid, batch_uuid, str(batch_type), _text(title, 240),
                max(0, int(requested_count or 0)), str(trigger or "manual"), _json(data or {}),
            ),
        )
        return _row(dict(cur.fetchone())) or {}


def _insert_runtime_run(
    cur,
    *,
    task_id: int,
    run_no: int,
    account_id: int | None,
    batch_id: int | None,
    resource_family: str,
    data: dict | None,
) -> dict:
    run_uuid = uuid.uuid4().hex
    cancellation_token = uuid.uuid4().hex
    cur.execute(
        f"""
        INSERT INTO {_table('operation_runs')} (
            run_uuid, task_id, run_no, source_system, source_id, status,
            batch_id, account_id, resource_family, cancellation_token, data
        ) VALUES (%s, %s, %s, 'native_operations', %s, 'queued', %s, %s, %s, %s, %s::jsonb)
        RETURNING *
        """,
        (
            run_uuid, int(task_id), int(run_no), run_uuid, batch_id, account_id,
            str(resource_family or "openai_interactive"), cancellation_token, _json(data or {}),
        ),
    )
    return dict(cur.fetchone())


def create_runtime_task(
    *,
    task_type: str,
    account_id: int | None,
    email: str,
    trigger: str = "manual",
    batch_id: int | None = None,
    batch_ordinal: int | None = None,
    parent_task_id: int | None = None,
    resource_family: str = "openai_interactive",
    data: dict | None = None,
) -> dict:
    """原子创建逻辑任务和第一次执行；活跃账号操作由数据库唯一索引防重。"""
    init()
    task_uuid = uuid.uuid4().hex
    account_value = int(account_id) if account_id else None
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            f"""
            INSERT INTO {_table('operation_tasks')} (
                task_uuid, source_system, source_id, batch_id, parent_task_id,
                task_type, target_type, target_id, account_id, email_snapshot,
                requested_action, status, target_status, current_stage,
                next_actions, trigger, data
            ) VALUES (
                %s, 'native_operations', %s, %s, %s,
                %s, 'account', %s, %s, %s,
                %s, 'queued', 'pending', 'queued',
                '[]'::jsonb, %s, %s::jsonb
            ) RETURNING *
            """,
            (
                task_uuid, task_uuid, batch_id, parent_task_id, str(task_type),
                account_value, account_value, str(email or "").strip(), str(task_type),
                str(trigger or "manual"), _json(data or {}),
            ),
        )
        task = dict(cur.fetchone())
        if not task.get("parent_task_id"):
            cur.execute(
                f"UPDATE {_table('operation_tasks')} SET root_task_id=id WHERE id=%s",
                (int(task["id"]),),
            )
        else:
            cur.execute(
                f"""
                UPDATE {_table('operation_tasks')} child
                SET root_task_id=COALESCE(parent.root_task_id, parent.id)
                FROM {_table('operation_tasks')} parent
                WHERE child.id=%s AND parent.id=child.parent_task_id
                """,
                (int(task["id"]),),
            )
        run = _insert_runtime_run(
            cur,
            task_id=int(task["id"]),
            run_no=1,
            account_id=account_value,
            batch_id=int(batch_id) if batch_id else None,
            resource_family=resource_family,
            data=data,
        )
        cur.execute(
            f"UPDATE {_table('operation_tasks')} SET last_run_id=%s WHERE id=%s",
            (int(run["id"]), int(task["id"])),
        )
        if batch_id:
            ordinal = int(batch_ordinal or 0)
            if ordinal <= 0:
                cur.execute(
                    f"SELECT COALESCE(MAX(ordinal), 0) + 1 AS n FROM {_table('operation_batch_items')} WHERE batch_id=%s",
                    (int(batch_id),),
                )
                ordinal = int(cur.fetchone()["n"])
            cur.execute(
                f"""
                INSERT INTO {_table('operation_batch_items')} (batch_id, task_id, run_id, ordinal)
                VALUES (%s, %s, %s, %s)
                """,
                (int(batch_id), int(task["id"]), int(run["id"]), ordinal),
            )
        task = _row(task) or {}
        task["run"] = _row(run) or {}
        return task


def retry_runtime_task(task_id: int, *, trigger: str = "manual_retry", data: dict | None = None) -> dict:
    """在同一逻辑任务下新建 attempt；不会制造第二条逻辑任务。"""
    init()
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            f"SELECT * FROM {_table('operation_tasks')} WHERE id=%s FOR UPDATE",
            (int(task_id),),
        )
        task = cur.fetchone()
        if not task:
            raise LookupError("任务不存在")
        if str(task.get("source_system") or "") != "native_operations":
            raise ValueError("历史兼容任务需先迁移为原生任务后再重跑")
        cur.execute(
            f"SELECT COALESCE(MAX(run_no), 0) + 1 AS n FROM {_table('operation_runs')} WHERE task_id=%s",
            (int(task_id),),
        )
        run_no = int(cur.fetchone()["n"])
        merged_data = dict(_decode(task.get("data")) or {})
        merged_data.update(data or {})
        merged_data["retry_trigger"] = str(trigger or "manual_retry")
        run = _insert_runtime_run(
            cur,
            task_id=int(task_id),
            run_no=run_no,
            account_id=int(task["account_id"]) if task.get("account_id") else None,
            batch_id=None,
            resource_family="openai_interactive",
            data=merged_data,
        )
        cur.execute(
            f"""
            UPDATE {_table('operation_tasks')}
            SET status='queued', target_status='pending', current_stage='queued',
                last_run_id=%s, error_category=NULL, error_code=NULL, error_message=NULL,
                completed_at=NULL, updated_at=now(), trigger=%s
            WHERE id=%s
            """,
            (int(run["id"]), str(trigger or "manual_retry"), int(task_id)),
        )
        return _row(run) or {}


def get_run(run_id: int) -> dict | None:
    init()
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            f"""
            SELECT r.*, t.task_type, t.email_snapshot, t.trigger, t.parent_task_id
            FROM {_table('operation_runs')} r
            JOIN {_table('operation_tasks')} t ON t.id=r.task_id
            WHERE r.id=%s
            """,
            (int(run_id),),
        )
        raw = cur.fetchone()
        return _row(dict(raw)) if raw else None


def active_run_for_account(account_id: int, resource_family: str = "openai_interactive") -> dict | None:
    init()
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            f"""
            SELECT r.*, t.email_snapshot, t.task_type
            FROM {_table('operation_runs')} r
            JOIN {_table('operation_tasks')} t ON t.id=r.task_id
            WHERE r.account_id=%s AND r.resource_family=%s
              AND r.status IN ('queued', 'running', 'cancelling', 'settling')
            ORDER BY r.id DESC LIMIT 1
            """,
            (int(account_id), str(resource_family)),
        )
        raw = cur.fetchone()
        return _row(dict(raw)) if raw else None


def list_queued_runs(*, limit: int = 500) -> list[dict]:
    init()
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            f"""
            SELECT r.*, t.email_snapshot, t.task_type
            FROM {_table('operation_runs')} r
            JOIN {_table('operation_tasks')} t ON t.id=r.task_id
            WHERE r.source_system='native_operations' AND r.status='queued'
              AND r.cancel_requested_at IS NULL
            ORDER BY r.created_at, r.id LIMIT %s
            """,
            (max(1, min(5000, int(limit or 500))),),
        )
        return [_row(dict(row)) or {} for row in cur.fetchall()]


def recover_interrupted_runtime_runs() -> int:
    """Web 进程启动时收口失去 worker 的 attempt；queued 由调度器继续认领。"""
    init()
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            f"""
            UPDATE {_table('operation_runs')}
            SET status='interrupted', completed_at=now(), heartbeat_at=now(),
                progress_stage='interrupted', error_message='执行进程已重启，原 attempt 中断'
            WHERE source_system='native_operations'
              AND status IN ('running', 'cancelling', 'settling')
            RETURNING id, task_id, account_id
            """
        )
        recovered = list(cur.fetchall())
        run_ids = [int(row["id"]) for row in recovered]
        task_ids = [int(row["task_id"]) for row in recovered]
        if task_ids:
            cur.execute(
                f"""
                UPDATE {_table('operation_tasks')}
                SET status='interrupted', current_stage='interrupted', completed_at=now(),
                    updated_at=now(), error_message='执行进程已重启，原 attempt 中断',
                    next_actions='[{{"action":"retry","label":"重新执行"}}]'::jsonb
                WHERE id = ANY(%s)
                """,
                (task_ids,),
            )
            cur.execute(
                f"""
                UPDATE {_table('operation_resources')}
                SET state='reconciliation_required',
                    detail=detail || '{{"reason":"worker_restart"}}'::jsonb
                WHERE run_id = ANY(%s) AND state='acquired'
                """,
                (run_ids,),
            )
            for row in recovered:
                event_uuid = uuid.uuid4().hex
                cur.execute(
                    f"""
                    INSERT INTO {_table('operation_events')} (
                        event_uuid, task_id, run_id, source_system, source_id,
                        level, stage, event_type, message, detail
                    ) VALUES (%s, %s, %s, 'native_operations', %s,
                              'WARNING', 'interrupted', 'run.interrupted',
                              '执行进程已重启，原 attempt 中断',
                              '{{"reason":"worker_restart"}}'::jsonb)
                    """,
                    (event_uuid, int(row["task_id"]), int(row["id"]), event_uuid),
                )
        cur.execute(
            f"DELETE FROM {_table('account_operation_leases')} WHERE run_id IN (SELECT id FROM {_table('operation_runs')} WHERE status='interrupted')"
        )
        account_ids = sorted({int(row["account_id"]) for row in recovered if row.get("account_id")})
        if account_ids:
            cur.execute(
                f"""
                UPDATE {postgres_store.qualified(record_store.ACCOUNTS.name)}
                SET codex_execution_status='empty', codex_active_run_id=NULL,
                    codex_last_run_status='interrupted',
                    codex_status=CASE WHEN codex_status='success' THEN codex_status ELSE 'interrupted' END,
                    updated_at=%s
                WHERE id = ANY(%s)
                """,
                (datetime.now().isoformat(timespec="seconds"), account_ids),
            )
        _refresh_batches(cur)
        return len(task_ids)


def refresh_runtime_batches() -> None:
    init()
    with _connect() as conn, conn.cursor() as cur:
        _refresh_batches(cur)


def mark_runtime_batch_empty(batch_id: int, *, status: str = "failed") -> None:
    init()
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            f"""
            UPDATE {_table('operation_batches')}
            SET status=%s, completed_at=now(),
                skipped_count=GREATEST(skipped_count, requested_count)
            WHERE id=%s AND NOT EXISTS (
                SELECT 1 FROM {_table('operation_batch_items')} item WHERE item.batch_id=%s
            )
            """,
            (str(status), int(batch_id), int(batch_id)),
        )


def set_runtime_batch_skipped(batch_id: int, skipped: list[dict]) -> None:
    """记录提交阶段未创建 run 的条目，避免批次计数看起来凭空少了账号。"""
    init()
    safe_items = list(skipped or [])[:5000]
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            f"""
            UPDATE {_table('operation_batches')}
            SET skipped_count=%s,
                data=data || %s::jsonb
            WHERE id=%s
            """,
            (len(safe_items), _json({"skipped": safe_items}), int(batch_id)),
        )
        _refresh_batches(cur)


def claim_run(run_id: int, *, execution_id: str, worker_pid: int) -> dict | None:
    """仅一个进程能把 queued attempt 原子认领为 running。"""
    init()
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            f"""
            UPDATE {_table('operation_runs')}
            SET status='running', execution_id=%s, worker_pid=%s,
                started_at=COALESCE(started_at, now()), heartbeat_at=now(), progress_stage='preflight'
            WHERE id=%s AND status='queued' AND cancel_requested_at IS NULL
            RETURNING *
            """,
            (str(execution_id), int(worker_pid), int(run_id)),
        )
        run = cur.fetchone()
        if not run:
            return None
        cur.execute(
            f"""
            UPDATE {_table('operation_tasks')}
            SET status='running', current_stage='preflight', updated_at=now()
            WHERE id=%s
            """,
            (int(run["task_id"]),),
        )
        return _row(dict(run)) or {}


def append_runtime_event(
    run_id: int,
    *,
    stage: str,
    message: str,
    state: str = "running",
    level: str = "INFO",
    event_type: str = "progress",
    detail: dict | None = None,
) -> dict:
    init()
    event_uuid = uuid.uuid4().hex
    stage_value = normalize_stage(stage)
    state_value = normalize_step_state(state)
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            f"SELECT task_id FROM {_table('operation_runs')} WHERE id=%s",
            (int(run_id),),
        )
        found = cur.fetchone()
        if not found:
            raise LookupError("执行实例不存在")
        task_id = int(found["task_id"])
        cur.execute(
            f"""
            INSERT INTO {_table('operation_events')} (
                event_uuid, task_id, run_id, source_system, source_id,
                level, stage, event_type, message, detail
            ) VALUES (%s, %s, %s, 'native_operations', %s, %s, %s, %s, %s, %s::jsonb)
            RETURNING *
            """,
            (
                event_uuid, task_id, int(run_id), event_uuid, str(level or "INFO").upper(),
                stage_value, str(event_type or "progress"), _text(message, 1400), _json(detail or {}),
            ),
        )
        event = dict(cur.fetchone())
        cur.execute(
            f"""
            UPDATE {_table('operation_runs')}
            SET progress_stage=%s,
                progress_steps=jsonb_set(progress_steps, %s, to_jsonb(%s::text), true),
                heartbeat_at=now()
            WHERE id=%s
            """,
            (stage_value, [stage_value], state_value, int(run_id)),
        )
        cur.execute(
            f"UPDATE {_table('operation_tasks')} SET current_stage=%s, updated_at=now() WHERE id=%s",
            (stage_value, task_id),
        )
        return _row(event) or {}


def heartbeat_run(run_id: int, lease_token: str = "") -> bool:
    init()
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            f"UPDATE {_table('operation_runs')} SET heartbeat_at=now() WHERE id=%s AND status IN ('running','cancelling','settling')",
            (int(run_id),),
        )
        changed = cur.rowcount > 0
        if lease_token:
            cur.execute(
                f"""
                UPDATE {_table('account_operation_leases')}
                SET heartbeat_at=now(), expires_at=now() + interval '10 minutes'
                WHERE run_id=%s AND lease_token=%s
                """,
                (int(run_id), str(lease_token)),
            )
        return changed


def acquire_account_lease(
    *, account_id: int, run_id: int, resource_family: str = "openai_interactive",
    ttl_seconds: int = 600,
) -> str | None:
    init()
    lease_token = uuid.uuid4().hex
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            f"DELETE FROM {_table('account_operation_leases')} WHERE expires_at < now()",
        )
        cur.execute(
            f"""
            INSERT INTO {_table('account_operation_leases')} (
                account_id, resource_family, run_id, lease_token, expires_at
            ) VALUES (%s, %s, %s, %s, now() + (%s * interval '1 second'))
            ON CONFLICT (account_id, resource_family) DO NOTHING
            RETURNING lease_token
            """,
            (int(account_id), str(resource_family), int(run_id), lease_token, max(60, int(ttl_seconds))),
        )
        row = cur.fetchone()
        return str(row["lease_token"]) if row else None


def release_account_lease(run_id: int, lease_token: str = "") -> bool:
    init()
    with _connect() as conn, conn.cursor() as cur:
        if lease_token:
            cur.execute(
                f"DELETE FROM {_table('account_operation_leases')} WHERE run_id=%s AND lease_token=%s",
                (int(run_id), str(lease_token)),
            )
        else:
            cur.execute(
                f"DELETE FROM {_table('account_operation_leases')} WHERE run_id=%s",
                (int(run_id),),
            )
        return cur.rowcount > 0


def request_run_cancel(run_id: int, *, reason: str = "用户手动停止") -> dict:
    """协作式取消：排队任务立即取消；运行任务进入 cancelling 等待检查点收口。"""
    init()
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            f"SELECT * FROM {_table('operation_runs')} WHERE id=%s FOR UPDATE",
            (int(run_id),),
        )
        run = cur.fetchone()
        if not run:
            raise LookupError("执行实例不存在")
        status = str(run.get("status") or "")
        if status in _TERMINAL_STATUSES:
            return _row(dict(run)) or {}
        target = "cancelled" if status == "queued" else "cancelling"
        completed_sql = ", completed_at=now()" if target == "cancelled" else ""
        cur.execute(
            f"""
            UPDATE {_table('operation_runs')}
            SET status=%s, cancel_requested_at=COALESCE(cancel_requested_at, now()),
                cancel_reason=%s, heartbeat_at=now(){completed_sql}
            WHERE id=%s RETURNING *
            """,
            (target, _text(reason, 500), int(run_id)),
        )
        updated = dict(cur.fetchone())
        task_status = "cancelled" if target == "cancelled" else "cancelling"
        task_stage = "complete" if target == "cancelled" else "cancelling"
        cur.execute(
            f"""
            UPDATE {_table('operation_tasks')}
            SET status=%s, current_stage=%s, updated_at=now(),
                completed_at=CASE WHEN %s='cancelled' THEN now() ELSE completed_at END
            WHERE id=%s
            """,
            (task_status, task_stage, task_status, int(run["task_id"])),
        )
        cur.execute(
            f"UPDATE {_table('account_operation_leases')} SET cancel_requested_at=now() WHERE run_id=%s",
            (int(run_id),),
        )
        event_uuid = uuid.uuid4().hex
        cur.execute(
            f"""
            INSERT INTO {_table('operation_events')} (
                event_uuid, task_id, run_id, source_system, source_id,
                level, stage, event_type, message, detail
            ) VALUES (%s, %s, %s, 'native_operations', %s,
                      'WARNING', %s, 'run.cancel_requested', %s, %s::jsonb)
            """,
            (
                event_uuid, int(run["task_id"]), int(run_id), event_uuid,
                task_stage, _text(reason, 1400),
                _json({"previous_status": status, "status": target}),
            ),
        )
        if run.get("batch_id"):
            _refresh_batches(cur)
        return _row(updated) or {}


def is_run_cancel_requested(run_id: int, cancellation_token: str = "") -> bool:
    init()
    with _connect() as conn, conn.cursor() as cur:
        params: list[Any] = [int(run_id)]
        token_clause = ""
        if cancellation_token:
            token_clause = " AND cancellation_token=%s"
            params.append(str(cancellation_token))
        cur.execute(
            f"""
            SELECT cancel_requested_at IS NOT NULL OR status IN ('cancelling','cancelled') AS requested
            FROM {_table('operation_runs')} WHERE id=%s{token_clause}
            """,
            params,
        )
        row = cur.fetchone()
        return not row or bool(row["requested"])


def mark_run_settling(run_id: int) -> bool:
    """Callback 已交给远端后进入有界对账阶段；保留 cancel_requested_at。"""
    init()
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            f"""
            UPDATE {_table('operation_runs')}
            SET status='settling', settling_at=COALESCE(settling_at, now()),
                progress_stage='credential_confirm', heartbeat_at=now()
            WHERE id=%s AND status IN ('running', 'cancelling')
            RETURNING task_id
            """,
            (int(run_id),),
        )
        row = cur.fetchone()
        if not row:
            return False
        cur.execute(
            f"""
            UPDATE {_table('operation_tasks')}
            SET status='settling', current_stage='credential_confirm', updated_at=now()
            WHERE id=%s
            """,
            (int(row["task_id"]),),
        )
        return True


def register_resource(
    run_id: int, *, resource_type: str, provider: str = "", external_id: str = "",
    detail: dict | None = None,
) -> dict:
    init()
    resource_uuid = uuid.uuid4().hex
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            f"""
            INSERT INTO {_table('operation_resources')} (
                resource_uuid, run_id, resource_type, provider, external_id, detail
            ) VALUES (%s, %s, %s, %s, %s, %s::jsonb)
            ON CONFLICT (run_id, resource_type, external_id) DO UPDATE
            SET state='acquired', released_at=NULL, detail=EXCLUDED.detail
            RETURNING *
            """,
            (
                resource_uuid, int(run_id), str(resource_type), str(provider),
                _text(external_id, 300), _json(detail or {}),
            ),
        )
        return _row(dict(cur.fetchone())) or {}


def release_resource(resource_id: int, *, state: str = "released", detail: dict | None = None) -> bool:
    init()
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            f"""
            UPDATE {_table('operation_resources')}
            SET state=%s, released_at=now(),
                detail=CASE WHEN %s::jsonb = '{{}}'::jsonb THEN detail ELSE detail || %s::jsonb END
            WHERE id=%s
            """,
            (str(state), _json(detail or {}), _json(detail or {}), int(resource_id)),
        )
        return cur.rowcount > 0


def finish_run(
    run_id: int,
    *,
    status: str,
    message: str = "",
    result_summary: dict | None = None,
    error: str | None = None,
) -> dict:
    init()
    status_value = _status(status)
    if status_value not in _TERMINAL_STATUSES:
        raise ValueError(f"非法终态: {status_value}")
    category, code, error_message = _error_fields(error or "", stage="complete", task_type="codex_retry")
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            f"""
            UPDATE {_table('operation_runs')}
            SET status=%s, completed_at=now(), heartbeat_at=now(), progress_stage='complete',
                duration_ms=GREATEST(0, (EXTRACT(EPOCH FROM (now() - COALESCE(started_at, created_at))) * 1000)::BIGINT),
                error_category=%s, error_code=%s, error_message=%s, result_summary=%s::jsonb
            WHERE id=%s RETURNING *
            """,
            (status_value, category, code, error_message, _json(result_summary or {}), int(run_id)),
        )
        run = cur.fetchone()
        if not run:
            raise LookupError("执行实例不存在")
        target_status = {
            "success": "credential_valid",
            "attention_required": "credential_pending_confirmation",
            "deactivated": "account_deactivated",
            "cancelled": "cancelled",
            "stopped": "cancelled",
        }.get(status_value, "failed")
        cur.execute(
            f"""
            UPDATE {_table('operation_tasks')}
            SET status=%s, target_status=%s, current_stage='complete', updated_at=now(),
                completed_at=now(), error_category=%s, error_code=%s, error_message=%s,
                next_actions=%s::jsonb
            WHERE id=%s
            """,
            (
                status_value, target_status, category, code, error_message,
                _json([] if status_value == "success" else [{"action": "retry", "label": "重新执行"}]),
                int(run["task_id"]),
            ),
        )
        event_uuid = uuid.uuid4().hex
        final_message = message or error_message or {
            "success": "Codex 凭证已确认并保存",
            "attention_required": "OAuth callback 已提交，凭证仍待确认",
            "cancelled": "执行已在安全检查点取消",
            "deactivated": "账号已确认不可用",
        }.get(status_value, f"执行结束：{status_value}")
        cur.execute(
            f"""
            INSERT INTO {_table('operation_events')} (
                event_uuid, task_id, run_id, source_system, source_id,
                level, stage, event_type, error_category, error_code, message, detail
            ) VALUES (%s, %s, %s, 'native_operations', %s, %s, 'complete', %s,
                      %s, %s, %s, %s::jsonb)
            """,
            (
                event_uuid, int(run["task_id"]), int(run_id), event_uuid,
                "INFO" if status_value == "success" else "WARNING",
                f"run.{status_value}", category, code, _text(final_message, 1400),
                _json({"status": status_value}),
            ),
        )
        cur.execute(
            f"""
            UPDATE {_table('operation_resources')}
            SET state='reconciliation_required',
                detail=detail || %s::jsonb
            WHERE run_id=%s AND state='acquired'
            """,
            (_json({"terminal_run_status": status_value}), int(run_id)),
        )
        cur.execute(f"DELETE FROM {_table('account_operation_leases')} WHERE run_id=%s", (int(run_id),))
        if run.get("batch_id"):
            _refresh_batches(cur)
        return _row(dict(run)) or {}


def verify() -> dict[str, Any]:
    """返回迁移不变量；ok=False 时不得切换生产 UI。"""
    init()
    with _connect() as conn, conn.cursor() as cur:
        checks: dict[str, int] = {}
        queries = {
            "legacy_registration_jobs": f"SELECT COUNT(*) FROM {postgres_store.qualified('registration_jobs')}",
            "mapped_registration_runs": f"SELECT COUNT(*) FROM {_table('operation_runs')} WHERE source_system='registration_jobs'",
            "legacy_account_tasks": f"SELECT COUNT(*) FROM {_table('account_action_tasks')}",
            "mapped_account_runs": f"SELECT COUNT(*) FROM {_table('operation_runs')} WHERE source_system='account_action_tasks'",
            "legacy_account_events": f"SELECT COUNT(*) FROM {_table('account_action_events')}",
            "mapped_account_events": f"SELECT COUNT(*) FROM {_table('operation_events')} WHERE source_system='account_action_events'",
            "orphan_runs": f"SELECT COUNT(*) FROM {_table('operation_runs')} r LEFT JOIN {_table('operation_tasks')} t ON t.id=r.task_id WHERE t.id IS NULL",
            "orphan_events": f"SELECT COUNT(*) FROM {_table('operation_events')} e LEFT JOIN {_table('operation_tasks')} t ON t.id=e.task_id WHERE t.id IS NULL",
            "duplicate_active_account_families": f"SELECT COUNT(*) FROM (SELECT account_id, resource_family FROM {_table('operation_runs')} WHERE account_id IS NOT NULL AND status IN ('queued','running','cancelling','settling') GROUP BY account_id, resource_family HAVING COUNT(*) > 1) AS duplicates",
            "terminal_run_leases": f"SELECT COUNT(*) FROM {_table('account_operation_leases')} lease JOIN {_table('operation_runs')} run ON run.id=lease.run_id WHERE run.status NOT IN ('queued','running','cancelling','settling')",
            "terminal_acquired_resources": f"SELECT COUNT(*) FROM {_table('operation_resources')} resource JOIN {_table('operation_runs')} run ON run.id=resource.run_id WHERE run.status NOT IN ('queued','running','cancelling','settling') AND resource.state='acquired'",
        }
        for key, sql in queries.items():
            cur.execute(sql)
            checks[key] = int(cur.fetchone()["count"])
        cur.execute(
            f"SELECT COUNT(*) FROM {_table('registration_attempts')} WHERE target_status='email_verification_pending'"
        )
        checks["pending_email_verification_attempts"] = int(cur.fetchone()["count"])
    ok = (
        checks["legacy_registration_jobs"] == checks["mapped_registration_runs"]
        and checks["legacy_account_tasks"] == checks["mapped_account_runs"]
        and checks["legacy_account_events"] == checks["mapped_account_events"]
        and checks["orphan_runs"] == 0
        and checks["orphan_events"] == 0
        and checks["duplicate_active_account_families"] == 0
        and checks["terminal_run_leases"] == 0
        and checks["terminal_acquired_resources"] == 0
    )
    return {"ok": ok, "checks": checks}
