# -*- coding: utf-8 -*-
"""Private storage for account-scoped Protocol authentication identities.

This module deliberately does not use :mod:`core.record_store`'s generic JSON
collections.  A stable auth identity contains device-level identifiers that
must not leak into ``registered_accounts.data``, compatibility exports, task
payloads, or ordinary account APIs.

The identity is opt-in and lazy.  Callers must explicitly choose the
``account_stable`` profile mode before invoking ``ensure_*``; this module does
not make that policy decision for them.
"""
from __future__ import annotations

import hashlib
import hmac
import json
import secrets
import threading
import uuid
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
import logging
from typing import Any

from config.browser import BROWSER_PROFILE_POOL, build_browser_environment
from core import postgres_store, record_store


logger = logging.getLogger(__name__)


_TABLE = "account_protocol_identities"
_CONTEXT_TABLE = "account_auth_run_contexts"
_AUDIT_TABLE = "account_auth_context_access_audits"
_PROFILE_VERSION = 1

# These are the only fields copied into the long-lived identity.  Geo, locale,
# timezone, session IDs, trace IDs, Sentinel state, and request-level values are
# intentionally reconstructed or generated for each BrowserSession.
_STABLE_PROFILE_FIELDS = (
    "screen_width",
    "screen_height",
    "device_pixel_ratio",
    "hardware_concurrency",
    "device_memory",
    "js_heap_size_limit",
    "browser_family",
    "browser_os",
    "navigator_platform",
    "navigator_vendor",
    "user_agent_data_platform",
    "safari_version",
    "safari_webkit_version",
    "chrome_major",
    "chrome_full_version",
    "user_agent",
    "send_client_hints",
    "sec_ch_ua",
    "sec_ch_ua_platform",
    "sec_ch_ua_platform_version",
    "sec_ch_ua_arch",
    "sec_ch_ua_bitness",
    "sec_ch_ua_model",
    "sec_ch_ua_full_version_list",
    "sec_ch_ua_mobile",
    "navigator_proto_samples",
    "document_key_samples",
    "window_key_samples",
    "script_src_samples",
    "window_feature_flags",
    "build_id",
)

_SESSION_IDENTIFIER_FIELDS = frozenset({
    "sentinel_sid",
    "oai_session_id",
    "auth_session_logging_id",
    "datadog_trace_id",
    "datadog_parent_id",
    "react_listening_key",
    "react_container_key",
    "react_resources_key",
    "roxy_debugger_address",
    "roxy_webdriver_url",
    "roxy_ws_endpoint",
    "roxy_browser_instance_id",
})
_PROXY_CONTEXT_FIELDS = frozenset({
    "provider", "mode", "region", "endpoint", "exit_ip", "acquired_at",
    "expires_at", "recent_until", "rotation_no",
})
_CONTEXT_READY_KEY = ""


class AccountAuthStorageError(RuntimeError):
    """A domain/storage error that is safe for the service layer to classify."""

    def __init__(self, code: str, message: str | None = None):
        self.code = str(code)
        super().__init__(f"{self.code}: {message}" if message else self.code)


@dataclass(frozen=True)
class BrowserIdentity:
    """The safe identity view passed to a BrowserSession.

    ``profile_key`` is intentionally absent.  It is only retained inside the
    private table so a normal service result cannot accidentally serialize it.
    """

    identity_id: int
    account_id: int
    profile_version: int
    profile_ref: str
    device_id: str
    browser_profile: dict[str, Any]

    def session_payload(self) -> dict[str, Any]:
        """Return the minimal immutable fields a BrowserSession needs."""
        return {
            "identity_id": self.identity_id,
            "account_id": self.account_id,
            "profile_version": self.profile_version,
            "profile_ref": self.profile_ref,
            "device_id": self.device_id,
            "browser_profile": json.loads(json.dumps(self.browser_profile, ensure_ascii=False)),
        }


_READY_KEY = ""
_LOCK = threading.RLock()


def _qualified() -> str:
    return postgres_store.qualified(_TABLE)


def init() -> None:
    """Create the private identity table and indexes idempotently."""
    global _READY_KEY
    database_url = postgres_store.database_url()
    if not database_url:
        raise AccountAuthStorageError("database_unconfigured", "账号认证身份存储需要 DATABASE_URL")
    ready_key = f"{database_url}::{postgres_store.schema_name()}"
    with _LOCK:
        if _READY_KEY == ready_key:
            return

        # The account row is created by record_store.  Ensure it exists before the
        # private table is used, but never add identity fields to that row.
        record_store.init()
        with postgres_store.connect() as conn, conn.cursor() as cur:
            cur.execute(
                f"""
                CREATE TABLE IF NOT EXISTS {_qualified()} (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    account_id BIGINT,
                    profile_version INTEGER NOT NULL,
                    profile_key TEXT NOT NULL,
                    device_id TEXT NOT NULL,
                    browser_profile JSONB NOT NULL,
                    profile_ref TEXT NOT NULL,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                    retired_at TIMESTAMPTZ,
                    UNIQUE(account_id, profile_version)
                )
                """
            )
            cur.execute(
                f"CREATE UNIQUE INDEX IF NOT EXISTS "
                f"{postgres_store.quote_identifier('uq_account_protocol_identities_active')} "
                f"ON {_qualified()} (account_id) WHERE retired_at IS NULL"
            )
            cur.execute(
                f"CREATE INDEX IF NOT EXISTS "
                f"{postgres_store.quote_identifier('idx_account_protocol_identities_account')} "
                f"ON {_qualified()} (account_id, retired_at)"
            )
        _READY_KEY = ready_key


def reset_ready() -> None:
    """Reset the schema cache after a test changes ``TURB_DB_SCHEMA``."""
    global _READY_KEY, _CONTEXT_READY_KEY
    _READY_KEY = ""
    _CONTEXT_READY_KEY = ""


def _material(profile_key: bytes, profile_version: int, label: str) -> bytes:
    message = f"turb-account-auth:v{int(profile_version)}:{label}".encode("utf-8")
    return hmac.new(profile_key, message, hashlib.sha256).digest()


def _choice(material: bytes, candidates: list[Any]) -> Any:
    if not candidates:
        raise AccountAuthStorageError("profile_candidates_empty")
    return candidates[int.from_bytes(material[:8], "big") % len(candidates)]


def _derive_identity(profile_key: str | bytes, profile_version: int = _PROFILE_VERSION) -> dict[str, Any]:
    """Derive one internally consistent, deterministic profile from a key.

    Candidate selection uses separate HMAC domains.  We never use email or
    account ID as a seed, and we do not slice one digest into every field.
    """
    if isinstance(profile_key, str):
        try:
            key_bytes = bytes.fromhex(profile_key)
        except ValueError as exc:
            raise AccountAuthStorageError("profile_key_invalid") from exc
    else:
        key_bytes = bytes(profile_key)
    if len(key_bytes) != 32:
        raise AccountAuthStorageError("profile_key_invalid")

    # Keep the candidate order stable within a profile version.  The current
    # browser implementation is macOS Chrome; the versioned split leaves room
    # for a later algorithm without silently drifting existing accounts.
    candidates = [dict(item) for item in BROWSER_PROFILE_POOL]
    screen = _choice(_material(key_bytes, profile_version, "screen"), candidates)
    cpu = _choice(
        _material(key_bytes, profile_version, "cpu"),
        [int(item["hardware_concurrency"]) for item in candidates],
    )
    memory = _choice(
        _material(key_bytes, profile_version, "memory"),
        [int(item["device_memory"]) for item in candidates],
    )
    heap = _choice(
        _material(key_bytes, profile_version, "heap"),
        [int(item["js_heap_size_limit"]) for item in candidates],
    )
    # OS and UA currently have one supported candidate.  They still have their
    # own domains so adding a second internally compatible candidate in v2 does
    # not couple the selector to another field.
    os_candidate = _choice(_material(key_bytes, profile_version, "os"), ["macOS"])
    ua_candidate = _choice(_material(key_bytes, profile_version, "ua"), ["chrome"])
    if os_candidate != "macOS" or ua_candidate != "chrome":  # pragma: no cover
        raise AccountAuthStorageError("profile_candidate_incompatible")

    base_profile = {
        "screen_width": int(screen["screen_width"]),
        "screen_height": int(screen["screen_height"]),
        "device_pixel_ratio": int(screen["device_pixel_ratio"]),
        "hardware_concurrency": cpu,
        "device_memory": memory,
        "js_heap_size_limit": heap,
    }
    complete = build_browser_environment({}, base_profile=base_profile)
    stable_profile = {
        key: json.loads(json.dumps(complete[key], ensure_ascii=False))
        for key in _STABLE_PROFILE_FIELDS
        if key in complete
    }
    device_bytes = bytearray(_material(key_bytes, profile_version, "device-id")[:16])
    # RFC 4122 UUID version/variant bits make the derived identifier look like
    # the UUID values generated by the existing BrowserSession implementation.
    device_bytes[6] = (device_bytes[6] & 0x0F) | 0x40
    device_bytes[8] = (device_bytes[8] & 0x3F) | 0x80
    return {
        "profile_version": int(profile_version),
        "profile_ref": _material(key_bytes, profile_version, "profile-ref").hex()[:12],
        "device_id": str(uuid.UUID(bytes=bytes(device_bytes))),
        "browser_profile": stable_profile,
    }


def _row_to_identity(row: dict[str, Any]) -> BrowserIdentity:
    try:
        profile = row.get("browser_profile") or {}
        if isinstance(profile, str):
            profile = json.loads(profile)
        if not isinstance(profile, dict):
            raise AccountAuthStorageError("identity_profile_invalid")
        profile = {
            key: json.loads(json.dumps(profile[key], ensure_ascii=False))
            for key in _STABLE_PROFILE_FIELDS
            if key in profile
        }
        required = {
            "screen_width", "screen_height", "device_pixel_ratio",
            "hardware_concurrency", "device_memory", "js_heap_size_limit",
        }
        if not required.issubset(profile):
            raise AccountAuthStorageError("identity_profile_incomplete")
        return BrowserIdentity(
            identity_id=int(row["id"]),
            account_id=int(row["account_id"]),
            profile_version=int(row["profile_version"]),
            profile_ref=str(row["profile_ref"]),
            device_id=str(row["device_id"]),
            browser_profile=profile,
        )
    except (KeyError, TypeError, ValueError, json.JSONDecodeError) as exc:
        raise AccountAuthStorageError("identity_row_invalid") from exc


def get_active_account_protocol_identity(account_id: int) -> BrowserIdentity | None:
    """Read the active identity without exposing the private profile key."""
    init()
    from psycopg.rows import dict_row

    with postgres_store.connect(row_factory=dict_row) as conn, conn.cursor() as cur:
        cur.execute(
            f"SELECT id, account_id, profile_version, device_id, browser_profile, profile_ref "
            f"FROM {_qualified()} WHERE account_id = %s AND retired_at IS NULL "
            f"ORDER BY profile_version DESC LIMIT 1",
            (int(account_id),),
        )
        row = cur.fetchone()
    return _row_to_identity(row) if row else None


def ensure_account_protocol_identity(
    account_id: int,
    *,
    profile_version: int = _PROFILE_VERSION,
) -> BrowserIdentity:
    """Return or create one stable identity while holding the account row lock."""
    init()
    account_id = int(account_id)
    profile_version = int(profile_version)
    if profile_version < 1:
        raise AccountAuthStorageError("profile_version_invalid")

    # Use a dict row factory only in this private module; record_store's normal
    # serializer never sees this table.
    from psycopg.rows import dict_row

    with postgres_store.connect(row_factory=dict_row) as conn, conn.cursor() as cur:
        cur.execute(
            f"SELECT id FROM {postgres_store.qualified('registered_accounts')} "
            f"WHERE id = %s FOR UPDATE",
            (account_id,),
        )
        if not cur.fetchone():
            raise AccountAuthStorageError("account_not_found", f"账号不存在: {account_id}")

        cur.execute(
            f"SELECT id, account_id, profile_version, device_id, browser_profile, profile_ref "
            f"FROM {_qualified()} WHERE account_id = %s AND retired_at IS NULL "
            f"ORDER BY profile_version DESC LIMIT 1",
            (account_id,),
        )
        existing = cur.fetchone()
        if existing:
            return _row_to_identity(existing)

        profile_key = secrets.token_bytes(32)
        derived = _derive_identity(profile_key, profile_version)
        cur.execute(
            f"""
            INSERT INTO {_qualified()}
                (account_id, profile_version, profile_key, device_id, browser_profile, profile_ref)
            VALUES (%s, %s, %s, %s, %s::jsonb, %s)
            ON CONFLICT (account_id, profile_version) DO NOTHING
            RETURNING id, account_id, profile_version, device_id, browser_profile, profile_ref
            """,
            (
                account_id,
                derived["profile_version"],
                profile_key.hex(),
                derived["device_id"],
                json.dumps(derived["browser_profile"], ensure_ascii=False),
                derived["profile_ref"],
            ),
        )
        inserted = cur.fetchone()
        if inserted:
            return _row_to_identity(inserted)

        # A defensive reread covers an identity inserted by a legacy process or
        # a future caller that does not take the account-row lock.
        cur.execute(
            f"SELECT id, account_id, profile_version, device_id, browser_profile, profile_ref "
            f"FROM {_qualified()} WHERE account_id = %s AND retired_at IS NULL "
            f"ORDER BY profile_version DESC LIMIT 1",
            (account_id,),
        )
        raced = cur.fetchone()
        if raced:
            return _row_to_identity(raced)
        raise AccountAuthStorageError("identity_create_failed")


def _raw_context_enabled() -> bool:
    from config import account as account_config

    return bool(getattr(account_config, "ACCOUNT_AUTH_RAW_CONTEXT_ENABLED", False))


def init_context() -> None:
    """Create the private per-run context table when its feature is enabled."""
    global _CONTEXT_READY_KEY
    database_url = postgres_store.database_url()
    if not database_url:
        raise AccountAuthStorageError("database_unconfigured", "认证上下文存储需要 DATABASE_URL")
    ready_key = f"{database_url}::{postgres_store.schema_name()}"
    with _LOCK:
        if _CONTEXT_READY_KEY == ready_key:
            return

        # Both foreign-key targets must exist before creating the context table.
        init()
        from core.storage import operation as operation_store

        operation_store.init()
        with postgres_store.connect() as conn, conn.cursor() as cur:
            cur.execute(
                f"""
                CREATE TABLE IF NOT EXISTS {postgres_store.qualified(_CONTEXT_TABLE)} (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    operation_run_id BIGINT NOT NULL REFERENCES
                        {postgres_store.qualified('operation_runs')}(id) ON DELETE CASCADE,
                    context_no INTEGER NOT NULL,
                    parent_context_id BIGINT REFERENCES
                        {postgres_store.qualified(_CONTEXT_TABLE)}(id) ON DELETE SET NULL,
                    context_schema_version INTEGER NOT NULL DEFAULT 1,
                    account_id BIGINT,
                    action TEXT NOT NULL,
                    driver TEXT NOT NULL,
                    auth_method TEXT,
                    route_attempt_no INTEGER,
                    session_no INTEGER NOT NULL,
                    protocol_identity_id BIGINT REFERENCES
                        {postgres_store.qualified(_TABLE)}(id) ON DELETE SET NULL,
                    protocol_profile_ref TEXT,
                    device_id TEXT,
                    session_identifiers JSONB NOT NULL DEFAULT '{{}}'::jsonb,
                    proxy_lease_id TEXT,
                    proxy_url TEXT,
                    proxy_context JSONB NOT NULL DEFAULT '{{}}'::jsonb,
                    roxy_profile_id TEXT,
                    status TEXT NOT NULL DEFAULT 'active',
                    result_code TEXT,
                    cleanup_status TEXT NOT NULL DEFAULT 'pending',
                    cleanup_error_code TEXT,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                    completed_at TIMESTAMPTZ,
                    expires_at TIMESTAMPTZ,
                    UNIQUE(operation_run_id, context_no)
                )
                """
            )
            cur.execute(
                f"CREATE INDEX IF NOT EXISTS "
                f"{postgres_store.quote_identifier('idx_account_auth_context_run')} "
                f"ON {postgres_store.qualified(_CONTEXT_TABLE)} (operation_run_id, context_no)"
            )
            cur.execute(
                f"CREATE INDEX IF NOT EXISTS "
                f"{postgres_store.quote_identifier('idx_account_auth_context_expiry')} "
                f"ON {postgres_store.qualified(_CONTEXT_TABLE)} (expires_at, id)"
            )
            cur.execute(
                f"""
                CREATE TABLE IF NOT EXISTS {postgres_store.qualified(_AUDIT_TABLE)} (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    context_id BIGINT REFERENCES
                        {postgres_store.qualified(_CONTEXT_TABLE)}(id) ON DELETE SET NULL,
                    operation_run_id BIGINT NOT NULL REFERENCES
                        {postgres_store.qualified('operation_runs')}(id) ON DELETE CASCADE,
                    actor TEXT NOT NULL,
                    purpose TEXT NOT NULL,
                    scope TEXT NOT NULL,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                    expires_at TIMESTAMPTZ
                )
                """
            )
            cur.execute(
                f"CREATE INDEX IF NOT EXISTS "
                f"{postgres_store.quote_identifier('idx_account_auth_context_audit_context')} "
                f"ON {postgres_store.qualified(_AUDIT_TABLE)} (context_id, created_at DESC)"
            )
            cur.execute(
                f"CREATE INDEX IF NOT EXISTS "
                f"{postgres_store.quote_identifier('idx_account_auth_context_audit_expiry')} "
                f"ON {postgres_store.qualified(_AUDIT_TABLE)} (expires_at, id)"
            )
        _CONTEXT_READY_KEY = ready_key


def _clean_allowlist(values: dict | None, allowed: frozenset[str]) -> dict[str, Any]:
    """Keep only explicitly classified JSON values; unknown keys are discarded."""
    if not isinstance(values, dict):
        return {}
    clean: dict[str, Any] = {}
    for key, value in values.items():
        name = str(key)
        if name not in allowed or value is None:
            continue
        if isinstance(value, (str, int, float, bool)):
            clean[name] = str(value)[:500] if isinstance(value, str) else value
    return clean


def operation_run_id_for_account_action_task(task_id: int | None) -> int | None:
    """Resolve the projected operation run for one legacy account task."""
    if not task_id or not _raw_context_enabled():
        return None
    init_context()
    from psycopg.rows import dict_row

    with postgres_store.connect(row_factory=dict_row) as conn, conn.cursor() as cur:
        cur.execute(
            f"SELECT id FROM {postgres_store.qualified('operation_runs')} "
            "WHERE source_system = 'account_action_tasks' AND source_id = %s "
            "ORDER BY id DESC LIMIT 1",
            (str(int(task_id)),),
        )
        row = cur.fetchone()
    return int(row["id"]) if row else None


def create_auth_run_context(
    *,
    operation_run_id: int,
    context_no: int | None = None,
    parent_context_id: int | None = None,
    account_id: int | None = None,
    action: str,
    driver: str,
    auth_method: str | None = None,
    route_attempt_no: int | None = None,
    session_no: int = 1,
    protocol_identity_id: int | None = None,
    protocol_profile_ref: str | None = None,
    device_id: str | None = None,
    session_identifiers: dict | None = None,
    proxy_lease_id: str | None = None,
    proxy_url: str | None = None,
    proxy_context: dict | None = None,
    roxy_profile_id: str | None = None,
) -> int | None:
    """Create one private context row; disabled mode is a strict no-op.

    When ``context_no`` is omitted, the operation run row is locked before the
    sequence is allocated.  This keeps allocation safe for a resumed run without
    relying on an unprotected ``MAX(context_no)`` race.
    """
    if not _raw_context_enabled():
        return None
    init_context()
    from psycopg.rows import dict_row

    from config import account as account_config

    retention_days = int(getattr(account_config, "ACCOUNT_AUTH_RAW_CONTEXT_RETENTION_DAYS", 30) or 0)
    expires_at = (
        datetime.now(timezone.utc) + timedelta(days=retention_days)
        if retention_days > 0 else None
    )
    identifiers = _clean_allowlist(session_identifiers, _SESSION_IDENTIFIER_FIELDS)
    route_context = _clean_allowlist(proxy_context, _PROXY_CONTEXT_FIELDS)
    operation_run_id = int(operation_run_id)
    session_no = max(1, int(session_no))
    with postgres_store.connect(row_factory=dict_row) as conn, conn.cursor() as cur:
        cur.execute(
            f"SELECT id FROM {postgres_store.qualified('operation_runs')} "
            f"WHERE id=%s{' FOR UPDATE' if context_no is None else ''}",
            (operation_run_id,),
        )
        if not cur.fetchone():
            raise AccountAuthStorageError("operation_run_not_found")
        if context_no is None:
            cur.execute(
                f"SELECT COALESCE(MAX(context_no), 0) + 1 AS next_no "
                f"FROM {postgres_store.qualified(_CONTEXT_TABLE)} WHERE operation_run_id=%s",
                (operation_run_id,),
            )
            context_no = int(cur.fetchone()["next_no"])
        context_no = max(1, int(context_no))
        cur.execute(
            f"""
            INSERT INTO {postgres_store.qualified(_CONTEXT_TABLE)} (
                operation_run_id, context_no, parent_context_id, account_id, action, driver,
                auth_method, route_attempt_no, session_no, protocol_identity_id,
                protocol_profile_ref, device_id, session_identifiers, proxy_lease_id,
                proxy_url, proxy_context, roxy_profile_id, expires_at
            ) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s::jsonb,%s,%s,%s::jsonb,%s,%s)
            ON CONFLICT (operation_run_id, context_no) DO NOTHING
            RETURNING id
            """,
            (
                operation_run_id, context_no, parent_context_id,
                int(account_id) if account_id is not None else None,
                str(action or "unknown")[:80], str(driver or "unknown")[:80],
                str(auth_method)[:80] if auth_method else None,
                int(route_attempt_no) if route_attempt_no is not None else None,
                session_no, int(protocol_identity_id) if protocol_identity_id is not None else None,
                str(protocol_profile_ref)[:80] if protocol_profile_ref else None,
                str(device_id)[:200] if device_id else None,
                json.dumps(identifiers, ensure_ascii=False),
                str(proxy_lease_id)[:160] if proxy_lease_id else None,
                str(proxy_url)[:2048] if proxy_url else None,
                json.dumps(route_context, ensure_ascii=False),
                str(roxy_profile_id)[:200] if roxy_profile_id else None,
                expires_at,
            ),
        )
        inserted = cur.fetchone()
        if inserted:
            return int(inserted["id"])
        cur.execute(
            f"SELECT id FROM {postgres_store.qualified(_CONTEXT_TABLE)} "
            "WHERE operation_run_id=%s AND context_no=%s",
            (operation_run_id, context_no),
        )
        existing = cur.fetchone()
    return int(existing["id"]) if existing else None


def get_auth_run_context(context_id: int) -> dict[str, Any] | None:
    """Private diagnostic read used by storage tests and future secret tooling."""
    if not _raw_context_enabled():
        return None
    init_context()
    from psycopg.rows import dict_row

    with postgres_store.connect(row_factory=dict_row) as conn, conn.cursor() as cur:
        cur.execute(
            f"SELECT * FROM {postgres_store.qualified(_CONTEXT_TABLE)} WHERE id=%s",
            (int(context_id),),
        )
        row = cur.fetchone()
    return dict(row) if row else None


def audit_auth_run_context_access(
    context_id: int | None,
    *,
    actor: str,
    purpose: str = "inspect",
    scope: str = "full",
) -> int | None:
    """Record a private-context read without copying any raw context values."""
    if not context_id or not _raw_context_enabled():
        return None
    init_context()
    actor_value = str(actor or "").strip()[:120]
    purpose_value = str(purpose or "inspect").strip()[:80]
    scope_value = str(scope or "full").strip()[:80]
    if not actor_value:
        raise AccountAuthStorageError("context_audit_actor_required")
    from psycopg.rows import dict_row

    with postgres_store.connect(row_factory=dict_row) as conn, conn.cursor() as cur:
        cur.execute(
            f"SELECT operation_run_id, expires_at FROM {postgres_store.qualified(_CONTEXT_TABLE)} WHERE id=%s",
            (int(context_id),),
        )
        context = cur.fetchone()
        if not context:
            return None
        cur.execute(
            f"""
            INSERT INTO {postgres_store.qualified(_AUDIT_TABLE)}
                (context_id, operation_run_id, actor, purpose, scope, expires_at)
            VALUES (%s,%s,%s,%s,%s,%s)
            RETURNING id
            """,
            (
                int(context_id), int(context["operation_run_id"]),
                actor_value, purpose_value, scope_value, context["expires_at"],
            ),
        )
        row = cur.fetchone()
    return int(row["id"]) if row else None


def get_auth_run_context_audited(
    context_id: int,
    *,
    actor: str,
    purpose: str = "inspect",
    scope: str = "full",
) -> dict[str, Any] | None:
    """Read one raw context only after writing a successful access audit."""
    if not context_id or not _raw_context_enabled():
        return None
    audit_id = audit_auth_run_context_access(
        context_id, actor=actor, purpose=purpose, scope=scope,
    )
    if not audit_id:
        return None
    return get_auth_run_context(context_id)


def finish_auth_run_context(
    context_id: int | None,
    *,
    status: str,
    result_code: str | None = None,
    cleanup_status: str = "done",
    cleanup_error_code: str | None = None,
) -> bool:
    """Close one context without touching account assets or task projection."""
    if not context_id or not _raw_context_enabled():
        return False
    init_context()
    final_status = str(status or "failed").strip().lower()
    if final_status not in {"active", "rotated", "success", "failed", "interrupted", "released"}:
        final_status = "failed"
    with postgres_store.connect() as conn, conn.cursor() as cur:
        cur.execute(
            f"""
            UPDATE {postgres_store.qualified(_CONTEXT_TABLE)}
            SET status=%s, result_code=%s, cleanup_status=%s,
                cleanup_error_code=%s,
                completed_at=CASE WHEN %s IN ('active') THEN completed_at ELSE COALESCE(completed_at, now()) END
            WHERE id=%s
            """,
            (
                final_status,
                str(result_code)[:160] if result_code else None,
                str(cleanup_status or "done")[:40],
                str(cleanup_error_code)[:120] if cleanup_error_code else None,
                final_status,
                int(context_id),
            ),
        )
        return cur.rowcount > 0


def cleanup_expired_auth_contexts(*, limit: int = 500) -> int:
    """Delete expired private contexts in bounded batches."""
    if not _raw_context_enabled():
        return 0
    init_context()
    limit = max(1, min(int(limit), 5000))
    with postgres_store.connect() as conn, conn.cursor() as cur:
        remaining = limit
        cur.execute(
            f"""
            DELETE FROM {postgres_store.qualified(_CONTEXT_TABLE)}
            WHERE id IN (
                SELECT id FROM {postgres_store.qualified(_CONTEXT_TABLE)}
                WHERE expires_at IS NOT NULL AND expires_at < now()
                ORDER BY expires_at, id LIMIT %s
            )
            """,
            (limit,),
        )
        removed = int(cur.rowcount)
        remaining = max(0, remaining - removed)
        if remaining:
            cur.execute(
                f"""
                DELETE FROM {postgres_store.qualified(_AUDIT_TABLE)}
                WHERE id IN (
                    SELECT id FROM {postgres_store.qualified(_AUDIT_TABLE)}
                    WHERE expires_at IS NOT NULL AND expires_at < now()
                    ORDER BY expires_at, id LIMIT %s
                )
                """,
                (remaining,),
            )
            removed += int(cur.rowcount)
        return removed


@dataclass
class AuthContextRecorder:
    """Best-effort recorder for Protocol sessions within one operation run."""

    operation_run_id: int
    account_id: int | None = None
    protocol_identity: Any = None
    _last_context_id: int | None = None
    _next_session_no: int = 1
    _contexts_by_session: dict[int, int] | None = None

    def __post_init__(self) -> None:
        if self._contexts_by_session is None:
            self._contexts_by_session = {}

    @classmethod
    def from_account_action_task(cls, task_id: int | None, *, account_id: int, protocol_identity=None):
        if not _raw_context_enabled():
            return None
        try:
            run_id = operation_run_id_for_account_action_task(task_id)
            return cls(run_id, account_id=account_id, protocol_identity=protocol_identity) if run_id else None
        except Exception as exc:
            logger.warning("[认证上下文] 无法关联 operation run，跳过原始上下文记录：%s", type(exc).__name__)
            return None

    def open_protocol_session(self, session, *, route_attempt_no: int, parent_context_id: int | None = None) -> int | None:
        identity = self.protocol_identity
        identity_id = getattr(identity, "identity_id", None)
        profile_ref = getattr(identity, "profile_ref", None)
        identifiers = {
            key: getattr(session, key, None)
            for key in _SESSION_IDENTIFIER_FIELDS
        }
        try:
            context_id = create_auth_run_context(
                operation_run_id=self.operation_run_id,
                parent_context_id=parent_context_id or self._last_context_id,
                account_id=self.account_id,
                action="token_refresh",
                driver="protocol_v2",
                auth_method="password",
                route_attempt_no=route_attempt_no,
                session_no=self._next_session_no,
                protocol_identity_id=identity_id,
                protocol_profile_ref=profile_ref,
                device_id=getattr(session, "device_id", None),
                session_identifiers=identifiers,
                proxy_url=getattr(session, "proxy", None),
                proxy_context={"mode": "session_proxy"},
            )
        except Exception as exc:
            logger.warning("[认证上下文] 会话记录失败，继续认证：%s", type(exc).__name__)
            return None
        self._next_session_no += 1
        if context_id:
            self._last_context_id = context_id
            self._contexts_by_session[id(session)] = context_id
        return context_id

    def finish_session(self, session, *, status: str, result_code: str | None = None) -> None:
        context_id = (self._contexts_by_session or {}).pop(id(session), None)
        if not context_id:
            return
        try:
            finish_auth_run_context(context_id, status=status, result_code=result_code)
        except Exception as exc:
            logger.warning("[认证上下文] 会话收口失败：%s", type(exc).__name__)


__all__ = [
    "AccountAuthStorageError",
    "AuthContextRecorder",
    "audit_auth_run_context_access",
    "BrowserIdentity",
    "cleanup_expired_auth_contexts",
    "create_auth_run_context",
    "ensure_account_protocol_identity",
    "finish_auth_run_context",
    "get_active_account_protocol_identity",
    "get_auth_run_context",
    "get_auth_run_context_audited",
    "init",
    "init_context",
    "operation_run_id_for_account_action_task",
    "reset_ready",
]
