# -*- coding: utf-8 -*-
"""RegistrationAttempt/RegistrationRun durable facts.

This module deliberately lives below the browser/registration drivers.  It records
the registration intent, every execution, and the one-way checkpoints needed to
resume safely after a process or network failure.  The legacy registration_jobs
table remains the execution compatibility table and is linked by ``attempt_id``.
"""
from __future__ import annotations

import json
import uuid
from contextlib import nullcontext
from datetime import datetime, timezone
from typing import Any, Iterable

from core import postgres_store, record_store


CHECKPOINTS = (
    "created",
    "email_claimed",
    "auth_started",
    "password_request_started",
    "password_confirmed",
    "otp_started",
    "otp_confirmed",
    "account_request_started",
    "account_confirmed",
    "token_obtained",
    "core_persisted",
    "postprocessing",
    "completed",
    "manual_reconcile",
    "failed",
)
CHECKPOINT_RANK = {value: index for index, value in enumerate(CHECKPOINTS)}
REMOTE_STATES = {"not_started", "request_unknown", "confirmed", "rejected"}
LOCAL_ACCOUNT_STATES = {"none", "token_obtained", "persisted"}
RUN_STATUSES = {
    "queued", "running", "success", "partial_success", "failed", "stopped",
    "cancelled", "interrupted", "request_unknown", "manual_reconcile",
}
TERMINAL_RUN_STATUSES = RUN_STATUSES - {"queued", "running"}
ACTIVE_RUN_STATUSES = ("queued", "running")

_READY_KEY = ""
_SENSITIVE_PARTS = ("password", "otp", "secret", "authorization", "cookie", "token")


def _table(name: str) -> str:
    return postgres_store.qualified(name)


def _connect():
    from psycopg.rows import dict_row

    return postgres_store.connect(row_factory=dict_row)


def _now() -> datetime:
    return datetime.now(timezone.utc)


def _json_value(value: Any, depth: int = 0) -> Any:
    """Keep event details useful without persisting credentials or OTP material."""
    if depth > 5:
        return "[truncated]"
    if isinstance(value, dict):
        result: dict[str, Any] = {}
        for raw_key, raw_value in list(value.items())[:120]:
            key = str(raw_key)[:100]
            if any(part in key.lower() for part in _SENSITIVE_PARTS):
                continue
            result[key] = _json_value(raw_value, depth + 1)
        return result
    if isinstance(value, (list, tuple)):
        return [_json_value(item, depth + 1) for item in list(value)[:120]]
    if isinstance(value, (str, bytes)):
        return str(value)[:2000]
    if value is None or isinstance(value, (bool, int, float)):
        return value
    return str(value)[:500]


def _json(value: Any) -> str:
    return json.dumps(_json_value(value), ensure_ascii=False, separators=(",", ":"))


def _decode(value: Any) -> Any:
    if isinstance(value, (dict, list)) or value is None:
        return value
    try:
        return json.loads(value)
    except (TypeError, ValueError):
        return value


def _row(row: dict | None) -> dict | None:
    if row is None:
        return None
    result = dict(row)
    for key in ("data", "detail", "result_summary"):
        if key in result:
            result[key] = _decode(result[key])
    for key, value in list(result.items()):
        if isinstance(value, datetime):
            result[key] = value.isoformat()
    return result


def reset_ready() -> None:
    global _READY_KEY
    _READY_KEY = ""


def init() -> None:
    """Create/upgrade registration facts without touching or deleting legacy rows."""
    global _READY_KEY
    if not postgres_store.enabled():
        raise RuntimeError("注册事实存储需要配置可用的 DATABASE_URL")
    record_store.init()
    ready_key = f"{postgres_store.database_url()}::{postgres_store.schema_name()}"
    if _READY_KEY == ready_key:
        return
    postgres_store.ensure_schema()
    with _connect() as conn, conn.cursor() as cur:
        attempts = _table("registration_attempts")
        jobs = _table(record_store.JOBS.name)
        cur.execute(
            f"""
            CREATE TABLE IF NOT EXISTS {attempts} (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                attempt_uuid TEXT NOT NULL UNIQUE,
                source_root_job_id BIGINT UNIQUE,
                email_snapshot TEXT NOT NULL DEFAULT '',
                account_id BIGINT,
                root_task_id BIGINT,
                checkpoint TEXT NOT NULL DEFAULT 'created',
                remote_identity_state TEXT NOT NULL DEFAULT 'not_started',
                remote_account_state TEXT NOT NULL DEFAULT 'not_started',
                local_account_state TEXT NOT NULL DEFAULT 'none',
                target_status TEXT NOT NULL DEFAULT 'pending',
                created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                completed_at TIMESTAMPTZ,
                data JSONB NOT NULL DEFAULT '{{}}'::jsonb
            )
            """
        )
        # operation.py already creates this table in current deployments.  These
        # additions make that existing table a compatible Attempt fact record.
        columns = (
            ("root_job_id", "BIGINT"),
            ("email", "TEXT"),
            ("email_source", "TEXT"),
            ("email_lease_id", "TEXT"),
            ("driver", "TEXT"),
            ("resume_policy", "TEXT"),
            ("active_execution_id", "TEXT"),
            ("heartbeat_at", "TIMESTAMPTZ"),
            ("terminal_at", "TIMESTAMPTZ"),
        )
        for name, sql_type in columns:
            cur.execute(f'ALTER TABLE {attempts} ADD COLUMN IF NOT EXISTS "{name}" {sql_type}')
        cur.execute(
            f"""
            UPDATE {attempts}
            SET root_job_id=COALESCE(root_job_id, source_root_job_id),
                email=COALESCE(NULLIF(email, ''), email_snapshot)
            WHERE root_job_id IS NULL OR email IS NULL OR email=''
            """
        )
        for name, sql_type in (
            ("attempt_id", "BIGINT"),
            ("execution_id", "TEXT"),
            ("action_type", "TEXT"),
            ("worker_pid", "INTEGER"),
            ("heartbeat_at", "TIMESTAMPTZ"),
            ("interrupted_at", "TIMESTAMPTZ"),
        ):
            cur.execute(f'ALTER TABLE {jobs} ADD COLUMN IF NOT EXISTS "{name}" {sql_type}')
        cur.execute(
            "SELECT 1 FROM pg_constraint WHERE conrelid=%s::regclass AND conname=%s",
            (f"{postgres_store.schema_name()}.registration_jobs", "registration_jobs_attempt_fk"),
        )
        if cur.fetchone() is None:
            cur.execute(
                f'ALTER TABLE {jobs} ADD CONSTRAINT "registration_jobs_attempt_fk" '
                f"FOREIGN KEY (attempt_id) REFERENCES {attempts}(id) NOT VALID"
            )
        cur.execute(
            f'CREATE INDEX IF NOT EXISTS "registration_attempts_checkpoint_idx" '
            f"ON {attempts} (checkpoint, updated_at)"
        )
        cur.execute(
            f'CREATE INDEX IF NOT EXISTS "registration_attempts_remote_account_idx" '
            f"ON {attempts} (remote_account_state, updated_at)"
        )
        cur.execute(
            f'CREATE UNIQUE INDEX IF NOT EXISTS "registration_attempts_root_job_idx" '
            f"ON {attempts} (root_job_id) WHERE root_job_id IS NOT NULL"
        )
        cur.execute(
            f"""
            CREATE TABLE IF NOT EXISTS {_table('registration_runs')} (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                run_uuid TEXT NOT NULL UNIQUE,
                attempt_id BIGINT NOT NULL REFERENCES {attempts}(id),
                job_id BIGINT,
                run_no INTEGER NOT NULL,
                action_type TEXT NOT NULL DEFAULT 'registration',
                status TEXT NOT NULL DEFAULT 'queued',
                execution_id TEXT,
                worker_pid INTEGER,
                heartbeat_at TIMESTAMPTZ,
                started_at TIMESTAMPTZ,
                completed_at TIMESTAMPTZ,
                duration_ms BIGINT,
                error_code TEXT,
                error_message TEXT,
                result_summary JSONB,
                created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                data JSONB NOT NULL DEFAULT '{{}}'::jsonb,
                UNIQUE(attempt_id, run_no)
            )
            """
        )
        cur.execute(
            "SELECT 1 FROM pg_constraint WHERE conrelid=%s::regclass AND conname=%s",
            (f"{postgres_store.schema_name()}.registration_runs", "registration_runs_job_fk"),
        )
        if cur.fetchone() is None:
            cur.execute(
                f'ALTER TABLE {_table("registration_runs")} ADD CONSTRAINT "registration_runs_job_fk" '
                f"FOREIGN KEY (job_id) REFERENCES {jobs}(id) NOT VALID"
            )
        cur.execute(
            f"""
            CREATE UNIQUE INDEX IF NOT EXISTS "registration_runs_job_idx"
            ON {_table('registration_runs')} (job_id) WHERE job_id IS NOT NULL
            """
        )
        cur.execute(
            f"""
            CREATE UNIQUE INDEX IF NOT EXISTS "registration_runs_active_idx"
            ON {_table('registration_runs')} (attempt_id)
            WHERE status IN ('queued', 'running')
            """
        )
        cur.execute(
            f"""
            CREATE TABLE IF NOT EXISTS {_table('registration_events')} (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                event_uuid TEXT NOT NULL UNIQUE,
                attempt_id BIGINT NOT NULL REFERENCES {attempts}(id),
                run_id BIGINT REFERENCES {_table('registration_runs')}(id),
                job_id BIGINT,
                created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                execution_id TEXT,
                checkpoint TEXT NOT NULL,
                event_type TEXT NOT NULL,
                level TEXT NOT NULL DEFAULT 'INFO',
                message TEXT,
                detail JSONB NOT NULL DEFAULT '{{}}'::jsonb
            )
            """
        )
        cur.execute(
            f'CREATE INDEX IF NOT EXISTS "registration_events_attempt_idx" '
            f"ON {_table('registration_events')} (attempt_id, id)"
        )
        cur.execute(
            f'CREATE INDEX IF NOT EXISTS "registration_runs_attempt_idx" '
            f"ON {_table('registration_runs')} (attempt_id, run_no)"
        )
    _READY_KEY = ready_key


def _validate_checkpoint(checkpoint: str) -> str:
    value = str(checkpoint or "").strip().lower()
    if value not in CHECKPOINT_RANK:
        raise ValueError(f"未知注册检查点: {checkpoint!r}")
    return value


def _validate_remote(value: str | None, current: str) -> str:
    if value is None:
        return current
    normalized = str(value).strip().lower()
    if normalized not in REMOTE_STATES:
        raise ValueError(f"未知远端状态: {value!r}")
    return normalized


def _attempt_from_cursor(cur, attempt_id: int) -> dict | None:
    cur.execute(f"SELECT * FROM {_table('registration_attempts')} WHERE id=%s", (int(attempt_id),))
    return _row(cur.fetchone())


def get_attempt(attempt_id: int) -> dict | None:
    init()
    with _connect() as conn, conn.cursor() as cur:
        return _attempt_from_cursor(cur, int(attempt_id))


def get_attempt_by_job(job_id: int) -> dict | None:
    init()
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            f"SELECT a.* FROM {_table('registration_attempts')} a "
            f"JOIN {_table('registration_jobs')} j ON j.attempt_id=a.id WHERE j.id=%s",
            (int(job_id),),
        )
        return _row(cur.fetchone())


def list_attempts(*, limit: int = 100, checkpoint: str | None = None) -> list[dict]:
    init()
    params: list[Any] = []
    where = ""
    if checkpoint is not None:
        where = " WHERE checkpoint=%s"
        params.append(_validate_checkpoint(checkpoint))
    params.append(max(1, int(limit)))
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            f"SELECT * FROM {_table('registration_attempts')}{where} "
            "ORDER BY id DESC LIMIT %s",
            params,
        )
        return [_row(item) for item in cur.fetchall()]


def create_attempt(
    email: str,
    *,
    email_source: str | None = None,
    root_job_id: int | None = None,
    attempt_uuid: str | None = None,
    driver: str | None = None,
    resume_policy: str | None = None,
    data: dict | None = None,
) -> dict:
    """Create an intent once; repeated calls for one root job return that intent."""
    init()
    address = str(email or "").strip()
    if not address:
        raise ValueError("注册 Attempt 必须有 email")
    identifier = str(attempt_uuid or uuid.uuid4())
    now = _now()
    with _connect() as conn, conn.cursor() as cur:
        if root_job_id is not None:
            cur.execute(
                f"""
                INSERT INTO {_table('registration_attempts')} (
                    attempt_uuid, source_root_job_id, root_job_id, email_snapshot, email,
                    email_source, driver, resume_policy, checkpoint,
                    remote_identity_state, remote_account_state, local_account_state,
                    target_status, created_at, updated_at, data
                ) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,'created','not_started','not_started','none','pending',%s,%s,%s::jsonb)
                ON CONFLICT (source_root_job_id) DO UPDATE SET
                    email_snapshot=CASE WHEN EXCLUDED.email_snapshot<>'' THEN EXCLUDED.email_snapshot ELSE {_table('registration_attempts')}.email_snapshot END,
                    email=COALESCE(NULLIF(EXCLUDED.email,''), {_table('registration_attempts')}.email),
                    email_source=COALESCE(EXCLUDED.email_source, {_table('registration_attempts')}.email_source),
                    driver=COALESCE(EXCLUDED.driver, {_table('registration_attempts')}.driver),
                    resume_policy=COALESCE(EXCLUDED.resume_policy, {_table('registration_attempts')}.resume_policy),
                    data={_table('registration_attempts')}.data || EXCLUDED.data,
                    updated_at=EXCLUDED.updated_at,
                    checkpoint=CASE WHEN {_table('registration_attempts')}.checkpoint IN ('unknown','') THEN 'created' ELSE {_table('registration_attempts')}.checkpoint END,
                    remote_identity_state=CASE WHEN {_table('registration_attempts')}.remote_identity_state IN ('unknown','') THEN 'not_started' ELSE {_table('registration_attempts')}.remote_identity_state END,
                    remote_account_state=CASE WHEN {_table('registration_attempts')}.remote_account_state IN ('unknown','') THEN 'not_started' ELSE {_table('registration_attempts')}.remote_account_state END,
                    local_account_state=CASE WHEN {_table('registration_attempts')}.local_account_state IN ('unknown','missing','') THEN 'none' ELSE {_table('registration_attempts')}.local_account_state END,
                    target_status=CASE WHEN {_table('registration_attempts')}.target_status IN ('unknown','') THEN 'pending' ELSE {_table('registration_attempts')}.target_status END
                RETURNING id
                """,
                (identifier, int(root_job_id), int(root_job_id), address, address,
                 str(email_source or "").strip() or None, str(driver or "").strip() or None,
                 str(resume_policy or "").strip() or None, now, now, _json(data or {})),
            )
        else:
            cur.execute(
                f"""
                INSERT INTO {_table('registration_attempts')} (
                    attempt_uuid, email_snapshot, email, email_source, driver, resume_policy,
                    checkpoint, remote_identity_state, remote_account_state, local_account_state,
                    target_status, created_at, updated_at, data
                ) VALUES (%s,%s,%s,%s,%s,%s,'created','not_started','not_started','none','pending',%s,%s,%s::jsonb)
                ON CONFLICT (attempt_uuid) DO UPDATE SET updated_at=EXCLUDED.updated_at
                RETURNING id
                """,
                (identifier, address, address, str(email_source or "").strip() or None,
                 str(driver or "").strip() or None, str(resume_policy or "").strip() or None,
                 now, now, _json(data or {})),
            )
        attempt_id = int(cur.fetchone()["id"])
        return _attempt_from_cursor(cur, attempt_id) or {}


def ensure_attempt_for_job(job_id: int, *, conn=None) -> dict:
    """Link a legacy job to its root Attempt, preserving the Attempt on retries."""
    init()
    own = conn is None
    with (_connect() if own else nullcontext(conn)) as active:
        with active.cursor() as cur:
            cur.execute(f"SELECT * FROM {_table('registration_jobs')} WHERE id=%s", (int(job_id),))
            job = _row(cur.fetchone())
            if not job:
                raise LookupError(f"注册任务不存在: {job_id}")
            if job.get("attempt_id"):
                attempt = _attempt_from_cursor(cur, int(job["attempt_id"]))
            else:
                root_id = int(job.get("root_job_id") or job_id)
                cur.execute(
                    f"SELECT id FROM {_table('registration_attempts')} WHERE root_job_id=%s OR source_root_job_id=%s LIMIT 1",
                    (root_id, root_id),
                )
                existing = cur.fetchone()
                if existing:
                    attempt_id = int(existing["id"])
                    # operation.py may have created a compatibility projection
                    # before this storage contract was installed.  Fill the new
                    # additive columns, but never rewind an advanced checkpoint.
                    cur.execute(
                        f"""
                        UPDATE {_table('registration_attempts')}
                        SET root_job_id=COALESCE(root_job_id,%s),
                            email_snapshot=CASE WHEN email_snapshot='' THEN %s ELSE email_snapshot END,
                            email=COALESCE(NULLIF(email,''),%s),
                            email_source=COALESCE(email_source,%s),
                            checkpoint=CASE WHEN checkpoint IN ('unknown','') THEN 'created' ELSE checkpoint END,
                            remote_identity_state=CASE WHEN remote_identity_state IN ('unknown','') THEN 'not_started' ELSE remote_identity_state END,
                            remote_account_state=CASE WHEN remote_account_state IN ('unknown','') THEN 'not_started' ELSE remote_account_state END,
                            local_account_state=CASE WHEN local_account_state IN ('unknown','missing','') THEN 'none' ELSE local_account_state END,
                            target_status=CASE WHEN target_status IN ('unknown','') THEN 'pending' ELSE target_status END,
                            updated_at=%s
                        WHERE id=%s
                        """,
                        (root_id, str(job.get("email") or ""), str(job.get("email") or ""),
                         str(job.get("email_source") or "").strip() or None, _now(), attempt_id),
                    )
                else:
                    now = _now()
                    cur.execute(
                        f"""
                        INSERT INTO {_table('registration_attempts')} (
                            attempt_uuid, source_root_job_id, root_job_id, email_snapshot, email,
                            email_source, checkpoint, remote_identity_state, remote_account_state,
                            local_account_state, target_status, created_at, updated_at, data
                        ) VALUES (%s,%s,%s,%s,%s,%s,'created','not_started','not_started','none','pending',%s,%s,%s::jsonb)
                        ON CONFLICT (source_root_job_id) DO UPDATE SET updated_at=EXCLUDED.updated_at
                        RETURNING id
                        """,
                        (str(uuid.uuid5(uuid.NAMESPACE_URL, f"turb-registration-attempt:{root_id}")),
                         root_id, root_id, str(job.get("email") or ""), str(job.get("email") or ""),
                         str(job.get("email_source") or "").strip() or None, now, now,
                         _json({"legacy_root_job_id": root_id})),
                    )
                    attempt_id = int(cur.fetchone()["id"])
                cur.execute(
                    f"UPDATE {_table('registration_jobs')} SET attempt_id=%s, updated_at=COALESCE(updated_at, %s) WHERE id=%s",
                    (attempt_id, _now().isoformat(timespec="seconds"), int(job_id)),
                )
                attempt = _attempt_from_cursor(cur, attempt_id)
            return attempt or {}


def _insert_event(
    cur,
    *,
    attempt_id: int,
    run_id: int | None,
    job_id: int | None,
    checkpoint: str,
    event_type: str,
    level: str,
    message: str | None,
    detail: dict | None,
    execution_id: str | None,
    event_uuid: str | None,
) -> None:
    event_key = str(event_uuid or uuid.uuid5(
        uuid.NAMESPACE_URL,
        f"turb-registration-event:{attempt_id}:{run_id or 0}:{checkpoint}:{event_type}:{execution_id or ''}",
    ))
    cur.execute(
        f"""
        INSERT INTO {_table('registration_events')} (
            event_uuid, attempt_id, run_id, job_id, created_at, execution_id,
            checkpoint, event_type, level, message, detail
        ) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s::jsonb)
        ON CONFLICT (event_uuid) DO NOTHING
        """,
        (event_key, int(attempt_id), int(run_id) if run_id is not None else None,
         int(job_id) if job_id is not None else None, _now(), str(execution_id or "").strip() or None,
         checkpoint, str(event_type or "checkpoint"), str(level or "INFO").upper(),
         str(message or "")[:2000] or None, _json(detail or {})),
    )


def advance_checkpoint(
    attempt_id: int,
    checkpoint: str,
    *,
    run_id: int | None = None,
    job_id: int | None = None,
    execution_id: str | None = None,
    event_type: str = "checkpoint",
    level: str = "INFO",
    message: str | None = None,
    detail: dict | None = None,
    remote_identity_state: str | None = None,
    remote_account_state: str | None = None,
    local_account_state: str | None = None,
    target_status: str | None = None,
    event_uuid: str | None = None,
) -> dict:
    """Advance one-way and append the audit event in one database transaction."""
    target = _validate_checkpoint(checkpoint)
    if local_account_state is not None and local_account_state not in LOCAL_ACCOUNT_STATES:
        raise ValueError(f"未知本地账号状态: {local_account_state!r}")
    init()
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(f"SELECT * FROM {_table('registration_attempts')} WHERE id=%s FOR UPDATE", (int(attempt_id),))
        current = _row(cur.fetchone())
        if current is None:
            raise LookupError(f"注册 Attempt 不存在: {attempt_id}")
        current_checkpoint = str(current.get("checkpoint") or "created").lower()
        if current_checkpoint not in CHECKPOINT_RANK:
            current_checkpoint = "created"
        if CHECKPOINT_RANK[target] < CHECKPOINT_RANK[current_checkpoint]:
            raise ValueError(f"检查点只能向前推进: {current_checkpoint} -> {target}")
        current_identity = str(current.get("remote_identity_state") or "not_started")
        current_identity = current_identity if current_identity in REMOTE_STATES else "not_started"
        current_account = str(current.get("remote_account_state") or "not_started")
        current_account = current_account if current_account in REMOTE_STATES else "not_started"
        current_local = str(current.get("local_account_state") or "none")
        current_local = current_local if current_local in LOCAL_ACCOUNT_STATES else "none"
        remote_identity = _validate_remote(remote_identity_state, current_identity)
        remote_account = _validate_remote(remote_account_state, current_account)
        local_state = local_account_state or current_local
        status = target_status
        if status is None:
            status = "completed" if target == "completed" else ("manual_reconcile" if target == "manual_reconcile" else str(current.get("target_status") or "pending"))
        completed_at = _now() if target in {"completed", "failed", "manual_reconcile"} else current.get("completed_at")
        cur.execute(
            f"""
            UPDATE {_table('registration_attempts')}
            SET checkpoint=%s, remote_identity_state=%s, remote_account_state=%s,
                local_account_state=%s, target_status=%s, updated_at=%s,
                completed_at=%s, terminal_at=%s,
                active_execution_id=COALESCE(%s, active_execution_id), heartbeat_at=%s
            WHERE id=%s
            """,
            (target, remote_identity, remote_account, local_state, status, _now(), completed_at,
             completed_at, str(execution_id or "").strip() or None, _now(), int(attempt_id)),
        )
        _insert_event(
            cur, attempt_id=int(attempt_id), run_id=run_id, job_id=job_id, checkpoint=target,
            event_type=event_type, level=level, message=message, detail=detail,
            execution_id=execution_id, event_uuid=event_uuid,
        )
        return _attempt_from_cursor(cur, int(attempt_id)) or {}


def mark_request_unknown(
    attempt_id: int,
    *,
    target: str,
    run_id: int | None = None,
    job_id: int | None = None,
    execution_id: str | None = None,
    message: str | None = None,
    detail: dict | None = None,
) -> dict:
    """Record an ambiguous remote result without rewinding a checkpoint."""
    field = {"identity": "remote_identity_state", "account": "remote_account_state"}.get(str(target).strip().lower())
    if field is None:
        raise ValueError("target 必须是 identity 或 account")
    init()
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(f"SELECT checkpoint FROM {_table('registration_attempts')} WHERE id=%s FOR UPDATE", (int(attempt_id),))
        row = cur.fetchone()
        if row is None:
            raise LookupError(f"注册 Attempt 不存在: {attempt_id}")
        checkpoint = str(row["checkpoint"] or "created")
        required_checkpoint = "password_request_started" if field == "remote_identity_state" else "account_request_started"
        if CHECKPOINT_RANK.get(checkpoint, 0) < CHECKPOINT_RANK[required_checkpoint]:
            raise ValueError(f"{target} 请求未知前必须先写入 {required_checkpoint} checkpoint")
        cur.execute(
            f"UPDATE {_table('registration_attempts')} SET {field}='request_unknown', target_status='request_unknown', updated_at=%s WHERE id=%s",
            (_now(), int(attempt_id)),
        )
        _insert_event(
            cur, attempt_id=int(attempt_id), run_id=run_id, job_id=job_id, checkpoint=checkpoint,
            event_type="request_unknown", level="WARNING", message=message or "远端请求结果未知",
            detail={**(detail or {}), "target": target}, execution_id=execution_id, event_uuid=None,
        )
        return _attempt_from_cursor(cur, int(attempt_id)) or {}


def mark_manual_reconcile(
    attempt_id: int,
    *,
    run_id: int | None = None,
    job_id: int | None = None,
    execution_id: str | None = None,
    message: str | None = None,
    detail: dict | None = None,
) -> dict:
    return advance_checkpoint(
        attempt_id, "manual_reconcile", run_id=run_id, job_id=job_id,
        execution_id=execution_id, event_type="manual_reconcile", level="WARNING",
        message=message or "需要人工对账", detail=detail, target_status="manual_reconcile",
    )


def start_run(
    attempt_id: int,
    *,
    job_id: int | None = None,
    action_type: str = "registration",
    execution_id: str | None = None,
    worker_pid: int | None = None,
    data: dict | None = None,
) -> dict:
    """Start one execution for an existing Attempt; retries add a Run only."""
    init()
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(f"SELECT id FROM {_table('registration_attempts')} WHERE id=%s FOR UPDATE", (int(attempt_id),))
        if cur.fetchone() is None:
            raise LookupError(f"注册 Attempt 不存在: {attempt_id}")
        if job_id is not None:
            cur.execute(f"SELECT id, attempt_id FROM {_table('registration_jobs')} WHERE id=%s", (int(job_id),))
            job = cur.fetchone()
            if job is None:
                raise LookupError(f"注册任务不存在: {job_id}")
            if job["attempt_id"] is not None and int(job["attempt_id"]) != int(attempt_id):
                raise ValueError("registration_job 已关联其他 Attempt")
            cur.execute(f"UPDATE {_table('registration_jobs')} SET attempt_id=%s WHERE id=%s", (int(attempt_id), int(job_id)))
            cur.execute(f"SELECT * FROM {_table('registration_runs')} WHERE job_id=%s", (int(job_id),))
            existing_job_run = cur.fetchone()
            if existing_job_run:
                return _row(existing_job_run) or {}
        cur.execute(
            f"SELECT * FROM {_table('registration_runs')} WHERE attempt_id=%s AND status IN ('queued','running') ORDER BY run_no DESC LIMIT 1",
            (int(attempt_id),),
        )
        active = cur.fetchone()
        if active:
            return _row(active) or {}
        cur.execute(f"SELECT COALESCE(MAX(run_no),0)+1 AS n FROM {_table('registration_runs')} WHERE attempt_id=%s", (int(attempt_id),))
        run_no = int(cur.fetchone()["n"])
        now = _now()
        cur.execute(
            f"""
            INSERT INTO {_table('registration_runs')} (
                run_uuid, attempt_id, job_id, run_no, action_type, status,
                execution_id, worker_pid, heartbeat_at, created_at, data
            ) VALUES (%s,%s,%s,%s,%s,'queued',%s,%s,%s,%s,%s::jsonb)
            RETURNING *
            """,
            (str(uuid.uuid4()), int(attempt_id), int(job_id) if job_id is not None else None, run_no,
             str(action_type or "registration"), str(execution_id or "").strip() or None,
             int(worker_pid) if worker_pid is not None else None, now, now, _json(data or {})),
        )
        return _row(cur.fetchone()) or {}


def retry_run(attempt_id: int, **kwargs: Any) -> dict:
    return start_run(attempt_id, **kwargs)


def list_runs(attempt_id: int, *, limit: int = 100) -> list[dict]:
    init()
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            f"SELECT * FROM {_table('registration_runs')} WHERE attempt_id=%s ORDER BY run_no DESC LIMIT %s",
            (int(attempt_id), max(1, int(limit))),
        )
        return [_row(item) for item in cur.fetchall()]


def get_run(run_id: int) -> dict | None:
    init()
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(f"SELECT * FROM {_table('registration_runs')} WHERE id=%s", (int(run_id),))
        return _row(cur.fetchone())


def finish_run(
    run_id: int,
    *,
    status: str,
    error_code: str | None = None,
    error_message: str | None = None,
    result_summary: dict | None = None,
) -> dict:
    value = str(status or "").strip().lower()
    if value not in RUN_STATUSES:
        raise ValueError(f"未知 RegistrationRun 状态: {status!r}")
    init()
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(f"SELECT * FROM {_table('registration_runs')} WHERE id=%s FOR UPDATE", (int(run_id),))
        run = cur.fetchone()
        if run is None:
            raise LookupError(f"RegistrationRun 不存在: {run_id}")
        completed = _now() if value in TERMINAL_RUN_STATUSES else None
        cur.execute(
            f"""
            UPDATE {_table('registration_runs')}
            SET status=%s, error_code=%s, error_message=%s, result_summary=%s::jsonb,
                completed_at=%s, duration_ms=CASE WHEN started_at IS NULL OR %s IS NULL THEN duration_ms
                    ELSE GREATEST(0, EXTRACT(EPOCH FROM (%s-started_at))*1000)::BIGINT END,
                heartbeat_at=%s
            WHERE id=%s
            RETURNING *
            """,
            (value, error_code, str(error_message or "")[:2000] or None, _json(result_summary or {}),
             completed, completed, completed, _now(), int(run_id)),
        )
        updated = _row(cur.fetchone()) or {}
        if value in {"request_unknown", "manual_reconcile"}:
            _insert_event(
                cur, attempt_id=int(run["attempt_id"]), run_id=int(run_id), job_id=run.get("job_id"),
                checkpoint="manual_reconcile", event_type=value, level="WARNING",
                message=error_message or value, detail=result_summary, execution_id=run.get("execution_id"), event_uuid=None,
            )
        return updated


def recover_interrupted_runs() -> int:
    """Close queued/running registration runs left by a crashed worker.

    Recovery only changes statuses and appends facts; it never deletes attempts,
    runs, events, or legacy jobs.
    """
    init()
    recovered = 0
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            f"SELECT * FROM {_table('registration_runs')} WHERE status IN ('queued','running') ORDER BY id FOR UPDATE"
        )
        rows = cur.fetchall()
        for run in rows:
            completed = _now()
            cur.execute(
                f"""
                UPDATE {_table('registration_runs')}
                SET status='interrupted', completed_at=%s,
                    error_code='worker_interrupted',
                    error_message='执行进程中断，等待同一 Attempt 恢复', heartbeat_at=%s
                WHERE id=%s
                """,
                (completed, completed, int(run["id"])),
            )
            cur.execute(
                f"UPDATE {_table('registration_attempts')} SET active_execution_id=NULL, updated_at=%s WHERE id=%s",
                (completed, int(run["attempt_id"])),
            )
            _insert_event(
                cur, attempt_id=int(run["attempt_id"]), run_id=int(run["id"]),
                job_id=run.get("job_id"), checkpoint="manual_reconcile", event_type="run_interrupted",
                level="WARNING", message="执行进程中断，等待同一 Attempt 恢复",
                detail={"run_id": int(run["id"])}, execution_id=run.get("execution_id"),
                event_uuid=str(uuid.uuid5(uuid.NAMESPACE_URL, f"turb-registration-interrupted:{run['id']}")),
            )
            recovered += 1
    return recovered


def persist_core_account(
    attempt_id: int,
    *,
    access_token: str,
    account: dict | None = None,
    run_id: int | None = None,
    job_id: int | None = None,
    execution_id: str | None = None,
) -> dict:
    """Persist the core account immediately after Token acquisition, atomically."""
    token = str(access_token or "").strip()
    if not token:
        raise ValueError("核心账号落库需要 access_token")
    init()
    payload = dict(account or {})
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(f"SELECT * FROM {_table('registration_attempts')} WHERE id=%s FOR UPDATE", (int(attempt_id),))
        attempt = _row(cur.fetchone())
        if attempt is None:
            raise LookupError(f"注册 Attempt 不存在: {attempt_id}")
        current_checkpoint = str(attempt.get("checkpoint") or "created")
        if current_checkpoint not in CHECKPOINT_RANK:
            current_checkpoint = "created"
        if CHECKPOINT_RANK[current_checkpoint] > CHECKPOINT_RANK["core_persisted"]:
            raise ValueError(f"核心账号落库不能倒退已完成的 checkpoint: {current_checkpoint}")
        email = str(payload.get("email") or attempt.get("email") or attempt.get("email_snapshot") or "").strip()
        if not email:
            raise ValueError("核心账号落库需要 email")
        payload["email"] = email
        payload["access_token"] = token
        account_id = payload.get("id") or attempt.get("account_id")
        if account_id is not None:
            cur.execute(
                f"SELECT * FROM {postgres_store.qualified(record_store.ACCOUNTS.name)} WHERE id=%s",
                (int(account_id),),
            )
            existing = cur.fetchone()
            if existing is None:
                payload["id"] = int(account_id)
                account_id = record_store.insert_row(record_store.ACCOUNTS, payload, conn=conn)
            else:
                record_store.patch_row(record_store.ACCOUNTS, int(account_id), payload, conn=conn)
        else:
            account_id = record_store.upsert_row_by(record_store.ACCOUNTS, "email", payload, conn=conn)
        now = _now()
        cur.execute(
            f"""
            UPDATE {_table('registration_attempts')}
            SET account_id=%s, checkpoint='core_persisted', local_account_state='persisted',
                remote_account_state='confirmed',
                target_status='account_available', updated_at=%s, heartbeat_at=%s,
                active_execution_id=COALESCE(%s, active_execution_id)
            WHERE id=%s
            """,
            (int(account_id), now, now, str(execution_id or "").strip() or None, int(attempt_id)),
        )
        _insert_event(
            cur, attempt_id=int(attempt_id), run_id=run_id, job_id=job_id, checkpoint="core_persisted",
            event_type="core_persisted", level="INFO", message="Token 后核心账号已落库",
            detail={"account_id": int(account_id), "email": email}, execution_id=execution_id, event_uuid=None,
        )
        if job_id is not None:
            cur.execute(f"UPDATE {_table('registration_jobs')} SET account_id=%s, attempt_id=%s WHERE id=%s", (int(account_id), int(attempt_id), int(job_id)))
        cur.execute(
            f"SELECT * FROM {postgres_store.qualified(record_store.ACCOUNTS.name)} WHERE id=%s",
            (int(account_id),),
        )
        saved = record_store.merge_row(record_store.ACCOUNTS, cur.fetchone())
        return {"attempt": _attempt_from_cursor(cur, int(attempt_id)), "account": saved, "account_id": int(account_id)}


def events(attempt_id: int, *, limit: int = 200) -> list[dict]:
    init()
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            f"SELECT * FROM {_table('registration_events')} WHERE attempt_id=%s ORDER BY id LIMIT %s",
            (int(attempt_id), max(1, int(limit))),
        )
        return [_row(item) for item in cur.fetchall()]


list_events = events
mark_checkpoint = advance_checkpoint
record_checkpoint = advance_checkpoint
persist_account_core = persist_core_account


def backfill(*, apply: bool = True) -> dict[str, int | bool]:
    """Backfill one Attempt and one Run per historical registration job, idempotently."""
    # A dry-run must remain read-only with respect to the new schema.  The legacy
    # row tables already exist through record_store; only --apply installs facts.
    if not apply:
        record_store.init()
    else:
        init()
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(f"SELECT * FROM {_table('registration_jobs')} ORDER BY id")
        jobs = [_row(item) for item in cur.fetchall()]
    if not apply:
        roots = {int(item.get("root_job_id") or item.get("id")) for item in jobs}
        return {"jobs": len(jobs), "attempts": len(roots), "runs": len(jobs), "applied": False}
    created_attempts = 0
    created_runs = 0
    for job in jobs:
        job_id = int(job["id"])
        before = get_attempt_by_job(job_id)
        attempt = ensure_attempt_for_job(job_id)
        if before is None:
            created_attempts += 1
        runs_before = list_runs(int(attempt["id"]), limit=10000)
        start_run(int(attempt["id"]), job_id=job_id, action_type=str(job.get("job_type") or "registration"), execution_id=job.get("execution_id"), worker_pid=job.get("worker_pid"))
        if len(list_runs(int(attempt["id"]), limit=10000)) > len(runs_before):
            created_runs += 1
    return {"jobs": len(jobs), "attempts": created_attempts, "runs": created_runs, "applied": True}


def verify() -> dict[str, Any]:
    """Check additive migration invariants; no writes beyond idempotent schema init."""
    init()
    with _connect() as conn, conn.cursor() as cur:
        queries = {
            "registration_jobs": f"SELECT COUNT(*) AS n FROM {_table('registration_jobs')}",
            "jobs_without_attempt": f"SELECT COUNT(*) AS n FROM {_table('registration_jobs')} WHERE attempt_id IS NULL",
            "orphan_runs": f"SELECT COUNT(*) AS n FROM {_table('registration_runs')} r LEFT JOIN {_table('registration_attempts')} a ON a.id=r.attempt_id WHERE a.id IS NULL",
            "orphan_events": f"SELECT COUNT(*) AS n FROM {_table('registration_events')} e LEFT JOIN {_table('registration_attempts')} a ON a.id=e.attempt_id WHERE a.id IS NULL",
            "invalid_checkpoints": f"SELECT COUNT(*) AS n FROM {_table('registration_attempts')} WHERE checkpoint NOT IN ({','.join(repr(item) for item in CHECKPOINTS)})",
            "duplicate_active_runs": f"SELECT COUNT(*) AS n FROM (SELECT attempt_id FROM {_table('registration_runs')} WHERE status IN ('queued','running') GROUP BY attempt_id HAVING COUNT(*)>1) x",
            "jobs_without_run": f"SELECT COUNT(*) AS n FROM {_table('registration_jobs')} j LEFT JOIN {_table('registration_runs')} r ON r.job_id=j.id WHERE r.id IS NULL",
        }
        checks: dict[str, int] = {}
        for key, sql in queries.items():
            cur.execute(sql)
            checks[key] = int(cur.fetchone()["n"])
    checks["mapped_jobs"] = checks["registration_jobs"] - checks["jobs_without_run"]
    ok = all(value == 0 for key, value in checks.items() if key not in {"registration_jobs", "mapped_jobs"})
    return {"ok": ok, "checks": checks}


__all__ = [
    "CHECKPOINTS", "CHECKPOINT_RANK", "REMOTE_STATES", "LOCAL_ACCOUNT_STATES", "RUN_STATUSES",
    "init", "reset_ready", "create_attempt", "ensure_attempt_for_job", "get_attempt", "get_attempt_by_job",
    "list_attempts", "advance_checkpoint", "mark_request_unknown", "mark_manual_reconcile", "start_run",
    "retry_run", "list_runs", "get_run", "finish_run", "persist_core_account", "events", "list_events",
    "mark_checkpoint", "record_checkpoint", "persist_account_core", "recover_interrupted_runs",
    "backfill", "verify",
]
